### ISSUE TITLE
Determine delphi_utils release process.

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast-indicators#1009]
`delphi_utils` is now released on pypi, and is currently synced with the HEAD of the `prod` branch for consistency with the indicators.

Going forward, we should decide how we want to release new versions of the utils while ensuring all the indicators and code that depends on the utils remain well synchronized. For example, breaking utils into their own repo gives us nice separation, but is probably riskier in terms of making sure we don't deploy a breaking change (we'd need to run tests against all the indicators somehow). Releasing utils from the HEAD of `prod` each time we merge to `prod`, ideally with some CI job that detects if files have changed (e.g. [using this github action](https://github.com/tj-actions/changed-files)), could be a good option since we can run all the tests with what _would be deployed_, and also automate out the deploy itself.

Will wait for Katie to return to discuss and decide.

**Comment by chinandrew** [comment]
another thing we can do is pin all the indicator utils versions in the dependencies, so then we can release new utils without worrying about breaking existing indicators until we explicitly update the version. The only downside is then we might have a bunch of indicators on different versions if we're not careful.

**Comment by krivard** [comment]
> Releasing utils from the HEAD of `prod` each time we merge to `prod`, ideally with some CI job

Yep, let's do that. Looping @sgratzl to consult -- we'd want a workflow setup that does something like this:

* Updates the version in `_delphi_utils_python/setup.py`
* Generates the PR from `main` to `prod` (different branch naming convention, apologies)
* Uploads `_delphi_utils_python` to PyPI on merge (so key auth probably)

Some open questions:
* I've been using a local copy of `auto-changelog` to generate the PR descriptions for `main`->`prod` PRs; should we start actually storing this information in a `CHANGELOG.md`?
* Do we bump the `_delphi_utils` version & upload on every PR to `prod`, or just the PRs that modify a file in the `_delphi_utils` tree?
* Do we track & tag a separate version number for the whole indicators repo? I kinda want to just so we can find things without having a bunch of no-op `delphi_utils` releases, but if it's hard, i'm sure we'll cope without it

`auto-changelog` template is as follows:
```
{{#each merges}}
- [`#{{id}}`]({{href}}), {{message}}
{{/each}}
```

**Comment by sgratzl** [comment]
questions
 * what is the plan regarding git tags / GitHub releases?
 * should the release workflow work on each push to prod? or when a tag is created? or trying to detect a merged release PR?
 *

**Comment by krivard** [comment]
I think we tag but don't publish releases -- a tarball of all the indicators doesn't really make sense as something a user would download.

I think we want the release workflow to just be an Action we can run which sets the whole process off, the same way we do frontend releases.
