### ISSUE TITLE
HHS data should include population-normalized signals, perhaps 7-day averages

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#1073]
The [HHS source](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/hhs.html) includes absolute counts of hospital admissions, but no `_prop` signals or `smoothed_` signals. This makes it inconvenient when I want to plot hospital admissions against other signals, like survey signals or any other per-population quantity.

- [x] smoothed variants
- [x] population-proportionate variants

**Comment by chinandrew** [comment]
Is this closed with #1199 ?

**Comment by krivard** [comment]
Yep!
