### ISSUE TITLE
Consider ingesting Corona Data Scraper or COVID Tracking testing data

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#112]
The [Corona Data Scraper](https://coronadatascraper.com/) project produces the  testing data that's used by Covid Act Now. They seem to have testing data for specific counties they scrape. They're also connected to the [COVID Atlas](https://covidatlas.com/).

We should investigate their testing data and see if they report enough counties to make it worthwhile to ingest.

Meanwhile, [COVID Tracking has an API](https://covidtracking.com/api) for state-level testing data, which forecasting is already using even though it's not in our API.

**Comment by RoniRos** [comment]
@krivard : That's correct.

@ryantibs : What is your thinking following our discussion with Igor?    Do you think we should go ahead with simple mirroring for now?   And/or do the one week project with CAN?

**Comment by RoniRos** [comment]
Based on the team leads discussion this morning, we should put CDS mirroring on indefinite hold.  Should this issue be suspended?

**Comment by krivard** [comment]
Yes -- I'll close it for now, and we can reopen at a later date if we find it is needed.
