### ISSUE TITLE
Validator check_se_not_missing_and_in_range not working for indicators with SE but no sample size

### ISSUE THREAD

**Issue by qx-teo** [cmu-delphi/covidcast-indicators#1122]
**Summary**
Validator check_se_not_missing_and_in_range uses the following formula to generate upper limits for standard errors:
`df_to_test.eval('se_upper_limit = (val * sample_size + 50)/(sample_size + 1)', inplace=True)`

This creates NAs when sample sizes aren't available, and automatically fails the test.

Left as an issue since currently all indicators either have both SE and N, or have neither of those (therefore bug does not appear in real-world tests)

**Possible Solutions**
Modifying code to provide warnings when N not available
Using only [0,50] limit rather than [0, min(50, val * (1 + eps))]
Finding alternative upper bound when N is not available

**Comment by qx-teo** [comment]
@nmdefries

**Comment by nmdefries** [comment]
Talked to Katie about this: It's not clear why we need to check SEs against a calculated upper limit. Verifying that SEs are positive and non-zero is sufficient, and we can just remove the upper limit bit.
