### ISSUE TITLE
Add MSA and HRR levels to SafeGraph data

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#114]
Though we do not ourselves use MSA-level data for forecasting, it may be of general interest to journalists and researchers interested in studying outbreaks in specific cities. Currently the SafeGraph pipeline does not do any aggregation to MSAs, only to states.

We should also add HRRs for completeness, since anyone using the HRR-level data from other sources may want to compare against HRR-level data from SafeGraph.

@jsharpna, maybe this is something that would be easy for you to do as you refactor the Python pipelines to use common geographic aggregation functions?

**Comment by capnrefsmmat** [comment]
Ping. It appears safegraph was refactored to use the geo utility, but I still don't see MSA and HRR in the API.

@chinandrew How hard is this to add to the SafeGraph codebase now that it uses the new geomapper?

**Comment by chinandrew** [comment]
> Ping. It appears safegraph was refactored to use the geo utility, but I still don't see MSA and HRR in the API.
> 
> @chinandrew How hard is this to add to the SafeGraph codebase now that it uses the new geomapper?

It doesn't look too complex. This is the current code, so I think it'd be adding the two additional conditionals for msa and hrr. @krivard what does the process look to approve + publish these signals once the indicator code is able to create additional resolutions?

```
    # Prepare geo resolution
    if geo_resolution == 'county':
        geo_transformed_df = df.copy()
        geo_transformed_df['geo_id'] = df['county_fips']
    elif geo_resolution == 'state':
        gmpr = GeoMapper()
        geo_transformed_df = gmpr.add_geocode(df,
                              from_col='county_fips',
                              from_code='fips',
                              new_code='state_id',
                              new_col='geo_id',
                              dropna=False)
    else:
        raise ValueError(
            f'`geo_resolution` must be one of {GEO_RESOLUTIONS}.')
```
