### ISSUE TITLE
Remove ArchiveDiffer from covid-act-now indicator

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#1163]
covid-act-now runs the ArchiveDiffer internally as part of the module's run() procedure. In order to switch Automation to run covid-act-now using the Indicator Runner, we need to remove this archiving code.

Once this fix goes in, we will need to carefully coordinate the release to prod with an update to the Automation Step definition.

**Comment by qx-teo** [comment]
Resolved with #1182
