### ISSUE TITLE
Special FIPS are labeled as NAN in the raw files from JHU-CSSE 

### ISSUE THREAD

**Issue by jingjtang** [cmu-delphi/covidcast-indicators#121]
- Eu Jing Noticed that there is no 70002 or 70003 in JHU-CSSE's raw file anymore. They are labeled as NAN now.
- There are extra locations such as Weber-Morgan, TriCounty, Bear River in Utah that were not considered in our pipeline. Their FIPS are also NAN in the raw file.

**Comment by dshemetov** [comment]
This issue may be resolved at this point? @jingjtang @jsharpna ?
