### ISSUE TITLE
Add structured logging to surveys indicator

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#1281]
Now that the surveys indicators is hooked in with the production deployment system, it makes sense to set up structured logging. The surveys indicator should join the rest of our production indicators in producing the following output for each run:
```
{"elapsed_time_in_seconds": <float>, "csv_export_count": <int>, "max_lag_in_days": <int>, "oldest_final_export_date": "YYYY-MM-DD", "event": "Completed indicator run", "logger": "delphiFacebook.run", "level": "info", "timestamp": "YYYY-MM-DDTHH:mm:ss.SSSZ"}
```

This output should be stored in a file configured in params. Production params should set this path to something in `/var/log/indicators`. We may need to add a corresponding mount to the docker run.

**Comment by nmdefries** [comment]
CTIS indicator has been removed https://github.com/cmu-delphi/covidcast-indicators/pull/1703
