### ISSUE TITLE
Build a contingency table framework for reporting more detailed symptom survey aggregates

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#129]
I think this is a task for August or later -- once we have the revised survey deployed and have extracted interesting univariate aggregates from it for the map.

Many researchers will be interested in using our survey data for purposes that do not require the full individual response data. To make the data useful to the widest possible audience, we could release data files containing aggregate contingency tables; the files would be suitable for public release and would let researchers study associations between multiple questions.

I'm imagining something like this:

1. A script reads the individual response data and codes column names and responses with more descriptive names.
2. Sub-scripts, one per output file, take this cleaned data and essentially do `group_by(stuff) %>% summarize(stuff)`. For example, you could imagine a script doing `group_by(epiweek, state, age, race) %>% summarize(mean(tested_positive), mean(cli), n(), ...)`. Each sub-script can focus on a different combination of variables of interest.
3. Each of the sub-scripts generates an output table that's written to CSV, with rows with inadequate sample size omitted.
4. We serve these CSVs in some canonical public location and also keep an archive of historical ones.

I'm not sure where we can serve the CSVs most easily -- perhaps a dedicated Git repo? or is there a common data repository service that does this kind of thing? -- but I think, in principle, this is fairly easy to do.

Also, is there a web-based data explorer tool that works well with this kind of data, so the general public could examine it?

**Comment by capnrefsmmat** [comment]
More aggregate data ideas:

* Frequency of reasons for testing (B10b), by county
* Frequency of medical care seeking (B7), by county
* Test rate and positivity rate by demographic features (age, race, occupation, probably marginally rather than jointly), by state (I assume not enough data for most counties)
* Frequency of each reason for *not* being tested (B12a), by demographic features
* Frequency of each unusual symptom among those who tested positive in past 14 days

These would surely be fascinating to many people, and could easily spawn papers.

**Comment by nmdefries** [comment]
Closed via #621.
