### ISSUE TITLE
New indicator: CDC COVID-19 Community Profile Report

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#1354]
The CDC publishes a community profile report which, among other things, includes total test volume. Since COVID Act Now will soon stop providing total test volume, this profile report seems to be a reasonable replacement.

**Data details**
 
[COVID-19 Community Profile Report](https://healthdata.gov/Health/COVID-19-Community-Profile-Report/gqxm-d9w9) on healthdata.gov

This report is updated *daily*. Most metrics count over a *rolling 7-day period*. This is suitable for producing covidcast signals which are 7-day averages, updated daily.

It includes the following metrics at the state level:
* FEMA region
* Population
* Cases and deaths: last 7 days (count, count per 100k population, % of national), % change from previous week, previous week (count, count per 100k population, % of national), cumulative (count, count per 100k population)
* Number of days of downward case trajectory
* Community transmission level (current week, previous week)
* Nucleic Acid Amplification Tests (NAAT; includes things like PCR): this week, previous week, and % or absolute change: test positivity (all and age-stratified), testing volume (count, count per 100k population), median test result latency, % of test results received in 3 or fewer days
* Emergency Department Visits: this week and absolute change from previous week: % of visits with diagnosed COVID-19 (all and age-stratified)
* Hospital utilization: this week and % or absolute change from previous week: COVID admissions (count, % of inpatient beds, and age-stratified count), % inpatient beds occupied (all and COVID-19), % staffed adult ICU beds occupied (all and COVID-19), % of ventilators in use (all and COVID-19)
* Hospital supply and staffing: this week and absolute change from previous week:  % hospitals unable to maintain X (N95 respirators, surgical masks, eye protection, single-use gowns, exam gloves), % hospitals with current staffing shortage
* Therapeutics: Monoclonal antibody courses administered (this week and % change from previous week), monoclonal antibody courses on hand
* Reporting and capacity: Number of CCNs, X among hospitals reporting this week (total inpatient beds, total staffed adult ICU beds, total ventilators), % CCNs reporting anything at least once this week, % CCNs reporting everything at least once this week, % CCNs ever reporting, % CCNs reporting COVID-19 admissions this week
* COVID-19 vaccinations: this week and % change from last week: Doses administered (count, count per 100k population), Booster doses administered
* COVID-19 vaccinations: cumulative: doses distributed (count, count per 100k population), doses administered (count, count per 100k population), people with at least 1 dose (count, % of population, age-stratified count, age-stratified % of population), people fully vaccinated (count, % of population, age-stratified count, age-stratified % of population), people with a booster since 2021-08-13 (count, % of population)
* COVID-19 vaccinations: this week, absolute change from previous week: age-stratified people initiating vaccination (count, % of population) 
* Age-stratified flu vaccination rate from 2018-2019

At the CBSA and county level, all of the state-level metrics plus the following:
* [county only] County type (large central metro, large fringe metro, medium metro, small metro, micropolitan, non-core)
* CBSA name & type
* Population (% of CBSA, % of state)
* IHE (>5000 full-time enrollment, full-time enrollment count and % of population)
* Rapid rise over the last 14 days (yes/no)
* Rapid riser category (new, recent, continuing)
* Area of concern category (Sustained hotspot, emerging hotspot, hotspot, high burden resolving, moderate burden resolving, moderate burden, low burden)
* Demographic details: % uninsured, % in poverty, % over age 65, average household size, % non-hispanic black, % hispanic, % non-hispanic native american / alaskan native, % non-hispanic asian, SVI score, CCVI score

**Comment by krivard** [comment]
January 2022 priority list:

- [ ] P0 hospital admissions
- [ ] P1 tests
- [ ] P1 vaccinations

**Comment by nmdefries** [comment]
Do we want to calculate tests per 100k population and hospital admissions per 100k population? We could also diff adjacent days to get raw counts.
