### ISSUE TITLE
Develop Change Healthcare data source (counts signal)

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#136]
- [x] Deliver CHC our user access list **by 9 July**
- [x] Create and send CHC a list of tools & libraries we need installed to their dev environment
- [x] Develop the research results pipeline
- [x] Get the pipeline statistically certified by CHC
- [x] Deploy the research results pipeline
- [x] Develop hookups to transfer research results to COVIDcast receiving

Other tasks as they arise.

**Comment by krivard** [comment]
We have counts; just chasing down the last few weird bits and then we can write them up as an indicator.

**Comment by korlaxxalrok** [comment]
Working on getting this to staging and Automated now 👍 

Additionally, the production deployment branch is in place so it will be an easy promotion once we validate in staging.

**Comment by chinandrew** [comment]
Not sure what the last bullet point above means, but is this done with #479? (or if further development is desired, should we make separate specific tickets?)

**Comment by krivard** [comment]
Yep!
