### ISSUE TITLE
MA has N/A values for HHS

### ISSUE THREAD

**Issue by qx-teo** [cmu-delphi/covidcast-indicators#1360]
**Actual Behavior:**

HHS seems to have N/A values at state level for Influenza signals sporadically: this seems to happen every week on Tuesdays.  The past few dates with N/A values are: 

- 8/3/2021
- 8/10/2021
- 8/17/2021
- 8/24/2021
- 8/31/2021
- 9/7/2021
- 9/14/2021
- 9/21/2021
- 9/28/2021
- 10/5/2021
- 10/19/2021

**Next Steps**
Add a filtering step in delphi_hhs that removes rows with geo_id == "ma", timestamp > "08-01-2021" and NA values.

**Comment by elray1** [comment]
Possibly related question -- is there some outlier suppression happening in the daily signal that is not present in the 7 day average signal? I am curious about what's going on in this plot: 
![image](https://user-images.githubusercontent.com/5132208/142445150-67164a25-6585-4908-8aa4-80531b174867.png)

Produced by this code:
```

ma_dat <- covidcast::covidcast_signals(
  data_source = "hhs",
  signal = c("confirmed_admissions_influenza_1d", "confirmed_admissions_influenza_1d_7dav"),
  geo_type = "state",
  geo_values = c("ma"))
ma_dat <- dplyr::bind_rows(ma_dat)

ggplot(data = ma_dat) +
  geom_line(mapping = aes(x = time_value, y = value, color = signal)) +
  facet_wrap( ~ geo_value) +
  theme_bw()
```

**Comment by krivard** [comment]
No, we don't do any outlier suppression, how alarming. Let me look into that and maybe open up a separate issue.
