### ISSUE TITLE
Support contingency table historical backfill

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/covidcast-indicators#1396]
At the moment, contingency tables are only available for 2021. We would like tables to also be available for 2020. To do so, we need to:

- [x] Make sure mental health indicators aren't generated for pre-Wave 4 surveys
- [ ] Report symptom, social distancing, and travel indicators
- [ ] Add in avoiding contact with others
- [ ] Report any other indicators the API reports for 2020
- [x] Make sure that empty tables aren't reported
- [ ] Add C7/C7a items

**Comment by nmdefries** [comment]
> Make sure mental health indicators aren't generated for pre-Wave 4 surveys

Added nohh_cmnty_cli and others_masked. Did not add inperson_school_<full/parttime>

**Comment by nmdefries** [comment]
> Add in avoiding contact with others

@capnrefsmmat which "avoiding contact" indicator/s were you thinking of?

The API reports the shopping, visit a restaurant, use public transit, work not-from-home, etc indicators based on C13, but those are already included in the contingency tables.

Item C11 (“In the past 24 hours, have you had direct contact with anyone who recently tested positive for COVID-19 (coronavirus)?”) is already reported in contingency tables, but not in the API.

Item C7 (“To what extent are you intentionally avoiding contact with other people?”) and replacement C7a (“how often did you intentionally avoid contact with other people?") were never used for any API indicators.

**Comment by capnrefsmmat** [comment]
I think we could add C7/C7a just because it's interesting, but it looks like we have all the important contact items already.
