### ISSUE TITLE
Hospital admissions scale is way off

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/covidcast-indicators#1399]
Something seems very off in the national-level hospital admissions scale.  (I suspect this deserves to be an issue on delphi-epidata or covidcast-indicators, @krivard feel free to move it over to those repos if appropriate.)

![Screen Shot 2021-12-08 at 11 18 21 AM](https://user-images.githubusercontent.com/732541/145247558-4ad564e7-403b-46cb-bb5c-f6fd580dca36.png)
 
On Dec 6, the number of new hospital admissions is ~4 times the number of new cases!  This is crazy, of course.  And if I look at the state-level numbers, they're way smaller in comparison:

![Screen Shot 2021-12-08 at 11 42 51 AM](https://user-images.githubusercontent.com/732541/145247961-f609bc8c-60ab-4abf-8d69-02d8d8358f53.png)

so, something seems very wrong.

**Comment by krivard** [comment]
Most likely something in the prop signals is off.

[Here’s a dashboard showing raw counts for HHS confirmed COVID-19 hospital admissions and JHU new cases, then counts per 100k.](https://delphi.cmu.edu/covidcast/dashboard/?date=20211127&sensor=hhs-confirmed_admissions_covid_1d#N4Ig9gTgJgphIC4DaIA2BLAdjA+gVhABo0tcA2Ik7HAdko2oA4QBdYgZwBcBDTmdxKAa4CCUAHd0UTgAtEeYjJjoA5jM6IATMQBecMIk4QArjGIRu4xADNuqdmZABjYwFtjqXugBuMG3YcAX2JhHAoxEElpOQQFECVVdS1dfUMTRwsrBFt7Rxd3T04fP2yAmGCqXDoIqNl5RWU1DQRtED0IAwQjU3NLf1zifI8vX36gkNIcZhqpOtiGxObW9s7ujL7Sgec3YaLRzaCKpzBMa1UBCNDw0AdMdkhEEAArGWMAWid2Bw+Ts4hXGBQHBYJxSGCYJy4TBuEAVULVG7g+7wBDxGTsH6ndD-QE4bhQVzoL7oE7sHDHbxSHAARiBAAcOnTYRMmIIQLdkY8Xu9Pt9jlicUCQWCIbgGWAmYEpUA)

| 2021-12-06 | admissions | new cases |
| -- | -- | -- |
| raw count | 7.1k | 192.9k |
| per 100k | 121.8 | 57.8 |
