### ISSUE TITLE
Repair all HHS hosp backissues for _prop signals in nation, hhs regions

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#1417]
Cleanup from #1407: Regenerate issues where the  #1399 bug was active. `hhs_hosp` supports as-of functionality in its params file so this should be fairly straightforward.

**Affected data:**

* source: hhs
* signals: `confirmed_admissions_covid_1d_prop`, `confirmed_admissions_covid_1d_prop_7dav`, `sum_confirmed_suspected_admissions_covid_1d_prop`, `sum_confirmed_suspected_admissions_covid_1d_prop_7dav`, `confirmed_admissions_influenza_1d_prop`, `confirmed_admissions_influenza_1d_prop_7dav`
* geo levels: hhs, nation
* time values: all
* issues: 20201116-20201209

**Comment by minhkhul** [comment]
Patched.
