### ISSUE TITLE
fb-survey - Reissue the smoothed_wvaccine_barrier_* and smoothed_wvaccine_barrier_*_has indicators back to Dec 12.

### ISSUE THREAD

**Issue by korlaxxalrok** [cmu-delphi/covidcast-indicators#1442]
**Actual Behavior:**

source: fb-survey

Due to #1439 we will need to reissue some dates.

**Comment by nmdefries** [comment]
Reissued all "smoothed_[w]vaccine_barrier_*" and "smoothed_[w]vaccine_barrier_*_has" indicators for dates Dec 12 2021-Dec 31 2021.

[backfill-vaccine-barriers-midDec2021.zip](https://github.com/cmu-delphi/covidcast-indicators/files/7823518/backfill-vaccine-barriers-midDec2021.zip)

**Comment by krivard** [comment]
I'll pick up upload for this

**Comment by krivard** [comment]
Done.
