### ISSUE TITLE
Update Quidel Covid  pipeline

### ISSUE THREAD

**Issue by jingjtang** [cmu-delphi/covidcast-indicators#1452]
We should have several updates to Quidel Covid Test data at the current stage of COVID. 
- Considering adding age group specific signals for Quidel Covid
- Add megaounty to Quidel Covid
- Add another minimum report threshold for Quidel Covid
- All the three items above can get historical reports especially the third one, we now have deletion support in our system
- Roni (maybe and I) will meet with Quidel next week? to see whether we can get variant information from Quidel (Like Flu)

**Comment by krivard** [comment]
[Ryan, Slack, 2022-01-10](https://delphi-org.slack.com/archives/C011CFX7TBR/p1641831874004000):
> Metrics:
> * [ ] for each availability threshold: 50, 40, 30, 20. (one table per threshold)
> * [ ] for each age group, and also for all-ages signal
> * [ ] % of locations available: average over time, for each county/state levels
> * [ ] correlations: timewise, average over locations, for each county/state levels

**Comment by krivard** [comment]
* [Live doc](https://docs.google.com/document/d/1WP4VJEois4D8qfeVeKCOJ9c4D7KHscDHzhQZgmuVvcA/edit#heading=h.kxccq395w8od)
* PDF version: [Quidel_AgeGroup_Signals.pdf](https://github.com/cmu-delphi/covidcast-indicators/files/7866184/Quidel_AgeGroup_Signals.pdf), generated 2022-01-13 16:40

Conclusions:
> * stick with the current 50 availability threshold for 1) consistency with what we have published 2) statistical consideration 3) not big difference if lower the threshold
> * Use the age group breakdown: 0-4, 5-17, 18-49, 50-64, 65+

**Comment by krivard** [comment]
Deletions are complete, but checks are showing suspicious counts.

Here's what was done:
1. Grab `issue,source,time_value,geo_type,signal,geo_value,value,stderr,sample_size` for quidel `covid_ag_smoothed_pct_positive` with issue<20220208 from MariaDB and store in a CSV file
2. Convert CSV file to batch issue format as "old data"
3. Reset the Quidel input cache. For each issue in the old data, in order chronologically, run the v0.3.2 (omicron) quidel indicator into a new export directory for that issue. Run the filesystem archiver, using the equivalent issue of the old data as the archivediffer cache. Now the contents of the export directory contain deletion annotations for any regions that were in the old data but are no longer generated by the new pipeline.
4. Grab only the export files for `covid_ag_smoothed_pct_positive` which have deletion annotations.
5. Convert the export files to deletion CSV format (`geo_id,value,stderr,sample_size,issue,time_value,geo_type,signal,source`)
6. Split into 1.5M batches
7. Delete 1 batch at a time using the `[covidcast] Cycle Quidel deletions` step. Wait for replication to recover between each batch. Spot-check a line in each batch before and after to make sure it exists before deleting and no longer exists after deleting.

The problem:
* The "old data" CSV had 37,719,716 lines
* The deletions CSV had 14,859,138 lines
* The DB is currently showing 21,616,771 rows for quidel `covid_ag_smoothed_pct_positive` with issue<20200208
* We'd expect the DB to show 22,860,086 rows instead
* We're short 1,243,315 rows, or just over 5%

Current plan:
- [ ] generate a "expected remaining" file containing old data minus deletions
- [ ] sample 200 rows from expected remaining
- [ ] see if these rows can be found in the DB. expect 5% missing. which ones?
- [ ] possibly check exhaustively 😥

**Comment by jingjtang** [comment]
@krivard what does this mean? Why do we have issues< 20200208? 
> * The DB is currently showing 21,616,771 rows for quidel `covid_ag_smoothed_pct_positive` with issue<20200208

**Comment by krivard** [comment]
typo!

**Comment by krivard** [comment]
apologies -- I could not get the file you generated to match against the database, but never followed up.
 
(also a lot of this is just notekeeping for me as I refine my analysis; I will continue to edit as I learn more)

**Comment by krivard** [comment]
Details above -- deletions confirmed correct.
