### ISSUE TITLE
Add retrospective gapfilling to CPR hospital admissions signals

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#1539]
Because the CPR only includes one (sometimes two) reference dates for each signal, and because the CPR is not published on weekends, the resulting COVIDcast signals are only available 5 days a week. See the green line in this timeseries chart:

![image](https://user-images.githubusercontent.com/1158666/156017860-035bf7dd-2802-4740-9179-8fcece51e88b.png)

We should use simple interpolation to fill these gaps **retrospectively** (once the next file becomes available). Extrapolation on days where no new files are posted is left as a future research project.

We'll need to do something like this:

* When computing the list of CPR files to process, extend the series backwards by one file ("additional CPR file")
* Process the CPR files into a df as usual
* Expand the df to cover a contiguous date sequence, NA-filling
* Impute the missing values
* Drop the per-signal reference dates in the additional CPR file
* Aggregate to nation, export, etc as usual

## Complication
The existing imputation utility in `delphi_utils.smooth` assumes we only ever impute a value for date X using data from dates Y<X. We will probably need to add support for some kind of symmetrical mode. Expected signal data for this change looks like `[x1, NA, NA, x4]` -- literally, since these gaps mostly occur at weekends. `x1` is from the additional CPR file, `x4` is from today's CPR file, and we want to publish the two imputed values and `x4`. This probably means a linear or other low-degree fit that doesn't need a lot of context to work.

This revision must be completed before we can begin showing county-level hospital admissions in the visualizations on the website.

**Comment by dshemetov** [comment]
Feels like I'm missing the context for this. Is this from new code somewhere? What is CPR?

**Comment by krivard** [comment]
Apologies for the name confusion -- CPR is the DSEW Community Profile Report, one of the new sets of signals developed as part of the omicron effort. [Pipeline code is here](https://github.com/cmu-delphi/covidcast-indicators/tree/main/dsew_community_profile)

**Comment by dshemetov** [comment]
So my initial thought is that getting this into the smooth util would require some involved math. A quick solution could be to use [`pandas.DataFrame.interpolate`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.interpolate.html#pandas.DataFrame.interpolate). 

Here is what `method="time"` (linear interpolation) looks like on a test dataset:

```py
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "time_value": pd.date_range("2022-01-01", "2022-04-01"),
    "value": 10*np.sin([i/3 if i % 7 >= 2 else np.nan for i in range(91)])
}).set_index("time_value")

import matplotlib.pyplot as plt

plt.figure()
plt.plot(df)
plt.figure()
plt.plot(df.interpolate(method="time"))
```
![image](https://user-images.githubusercontent.com/1810426/157105421-90a6f0ed-42a0-4abc-8dfb-42b4fae11f3d.png)

Here is what `method="cubic"` looks like:
![image](https://user-images.githubusercontent.com/1810426/157105752-4cca2c67-8dd1-4a7f-9747-ce8f6627d5d4.png)

**Comment by dshemetov** [comment]
This is what the plot in the OP looks like with cubic interpolation:
![image](https://user-images.githubusercontent.com/1810426/157308913-9c036e3c-1ebc-461e-8eaa-86bc70ec1483.png)

**Comment by krivard** [comment]
Solving this will require reading in additional, already-processed files, which seems complicated. We've discarded "read in extra files" before as a solution for the "volume and positivity are technically for different reference dates" problem, so we should consider avoiding it here as well.

Alternatives:
* Make the frontend do interpolation
* Make users do interpolation
* Make the API do interpolation
