### ISSUE TITLE
[DSEW CPR] Extend interpolation to the final signal

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/covidcast-indicators#1576]
#1555 extended interpolation to all signals except `covid_naat_pct_positive_7dav`. With some more complex caching logic, we can extend it to this final signal. See [the design document](https://docs.google.com/document/d/1KRm0AAE8jUIqazw4AuUBrz0unIZgeJe9BC7VkTB9oJY/edit#) for the latest plans.

**Comment by nmdefries** [comment]
`dsew-cpr` has been removed https://github.com/cmu-delphi/covidcast-indicators/pull/1871. Assuming we don't want to patch this in.

**Comment by dshemetov** [comment]
We probably don't have the dev resources to patch this in any time soon, so I'd vote to close.
