### ISSUE TITLE
Fix prod for dsew-cpr

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#1600]
* Tuesday we released 3.11
* Wednesday we reverted the release
* Now we want to release 3.12

Possible procedure:
1. Merge https://github.com/cmu-delphi/covidcast-indicators/pull/1594
2. Verify output in staging is as expected
3. check out prod locally, `rebase -i covidcast-indicators/v0.3.11` and drop any commits that mention reverting 3.11
4. force-push to origin
5. create patch release via github actions
6. created release PR should be for 3.12
7. Merge release PR
8. create sync main PR should be for 3.12
9. Merge sync main PR

**Comment by nmdefries** [comment]
`dsew-cpr` has been removed https://github.com/cmu-delphi/covidcast-indicators/pull/1871
