### ISSUE TITLE
[DSEW CPR] Improve test coverage

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/covidcast-indicators#1619]
At least with `fetch_listing`, the "date range" and "all" parameter settings are not covered. See [here](https://github.com/cmu-delphi/covidcast-indicators/pull/1615#pullrequestreview-970441618).

**Comment by nmdefries** [comment]
`dsew-cpr` has been removed https://github.com/cmu-delphi/covidcast-indicators/pull/1871
