### ISSUE TITLE
Fix issue with Hospital Claims test

### ISSUE THREAD

**Issue by neul3** [cmu-delphi/covidcast-indicators#1667]
When running the claims_hosp on the staging server the following error is given:
`File "/mnt/data2/indicators/runtime/claims_hosp/secrets.py", line 3, in claims
    USER = hosp
NameError: name 'hosp' is not defined`

**Comment by jingjtang** [comment]
> When running the claims_hosp on the staging server the following error is given:
> `File "/mnt/data2/indicators/runtime/claims_hosp/secrets.py", line 3, in claims USER = hosp NameError: name 'hosp' is not defined`

Why is there a `secrets.py`? I think we have already switched to `params.json` to store all the secrets.

**Comment by neul3** [comment]
> > When running the claims_hosp on the staging server the following error is given:
> > `File "/mnt/data2/indicators/runtime/claims_hosp/secrets.py", line 3, in claims USER = hosp NameError: name 'hosp' is not defined`
> 
> @neul3 Why is there a `secrets.py`? I think we have already switched to `params.json` to store all the secrets.

@jingjtang thats a good question, I don't have any familiarity with the indicator itself. I can ping Katie on next steps or try and investigate myself?

**Comment by korlaxxalrok** [comment]
`secrets.py` was added as part of the very first attempt to modify the indicator. The idea/goal was that the indicator was using a "secrets file mechanism" in its original form, and that there would be less friction if we mirrored that functionality in the new version.

It shouldn't be needed if we've switched to `params.json`, though maybe it is somewhat of a mystery as to what is looking at that file when running with `env/bin/python -m delphi_claims_hosp`?

**Comment by jingjtang** [comment]
> 

Thanks @korlaxxalrok. So what you recommend us to work towards this issue? I doubt for some reason that stagging test do not run the current pipline. When and where could we check that?

**Comment by jingjtang** [comment]
> > > When running the claims_hosp on the staging server the following error is given:
> > > `File "/mnt/data2/indicators/runtime/claims_hosp/secrets.py", line 3, in claims USER = hosp NameError: name 'hosp' is not defined`
> > 
> > 
> > @neul3 Why is there a `secrets.py`? I think we have already switched to `params.json` to store all the secrets.
> 
> @jingjtang thats a good question, I don't have any familiarity with the indicator itself. I can ping Katie on next steps or try and investigate myself?

It would be helpful if @neul3 can check and tell me what I need to do with the stagging test. Where does the code live? Could you help to check whether it run the current claims_hosp pipeline(which is exactly the one that we can see in the `main` branch under `claims_hosp`)?  If not, is that a mistake or intended?

**Comment by neul3** [comment]
I'm looking into it now, but maybe @korlaxxalrok would have more immediate insight?

**Comment by korlaxxalrok** [comment]
Check #1668 for a possible path forward. I think we can deprecate that `secrets.py` mechanism. Also, the json params template wasn't getting deployed. Lets start with this and figure out the mystery of why any recent versions of the indicator would care about the secrets.py file anyway.

**Comment by neul3** [comment]
After merging #1668 some more staging tests have resulted in the following: 
`Traceback (most recent call last):
  File "/home/indicators/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/indicators/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/data2/indicators/runtime/claims_hosp/delphi_claims_hosp/__main__.py", line 11, in <module>
    run_module(read_params())  # pragma: no cover
  File "/mnt/data2/indicators/runtime/claims_hosp/delphi_claims_hosp/run.py", line 61, in run_module
    download(params["indicator"]["ftp_credentials"],
  File "/mnt/data2/indicators/runtime/claims_hosp/delphi_claims_hosp/download_claims_ftp_files.py", line 67, in download
    file_time = get_timestamp(fileattr.filename)
  File "/mnt/data2/indicators/runtime/claims_hosp/delphi_claims_hosp/download_claims_ftp_files.py", line 34, in get_timestamp
    return datetime.datetime.strptime(''.join(m.groups()), "%Y%m%d%H%M")
  File "/home/indicators/.pyenv/versions/3.8.2/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/home/indicators/.pyenv/versions/3.8.2/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '105302020' does not match format '%Y%m%d%H%M'`

**Comment by jingjtang** [comment]
@neul3 @korlaxxalrok Where can I check the code of the staging test? The error that @neul3 showed seems that we do not have the right `params.json` file for the staging test.

**Comment by korlaxxalrok** [comment]
@jingjtang I think it is in the standard deployment location on the staging host.

**Comment by jingjtang** [comment]
@korlaxxalrok @neul3 Let's check #1673 to see whether it can solve the problem.
