### ISSUE TITLE
Productionize-doctor-visits

### ISSUE THREAD

**Issue by jingjtang** [cmu-delphi/covidcast-indicators#1676]
Productionize doctor visitis

- Switch from print() to logger
- Configure delphi_utils.validator to replicate as much of Maria's validation routines as is feasible

What to do about data fetching:
* The current doctor-visits pipeline wraps everything in a shell script.
* The current covidcast-indicators delphi_utils.runner pipeline uses Python for this.
* Move everything into delphi_utils.runner: -requires more development effort to add data fetching, +makes pipelines uniform
   * [x] refactor data fetching
   * [x] refactor secrets into params.json
   * [x] Automation step calls `python -m delphi_utils.runner delphi_doctor_visits`

#1677

**Comment by melange396** [comment]
putting this back on our radar

**Comment by minhkhul** [comment]
All done.
