### ISSUE TITLE
NCHS Upload lag discrepancy 

### ISSUE THREAD

**Issue by neul3** [cmu-delphi/covidcast-indicators#1678]
After experiencing a large gap in uploads NCHS is experiencing an unusual gap between the indicator and sircal lag. 
<img width="876" alt="Screen Shot 2022-08-09 at 10 50 37 AM" src="https://user-images.githubusercontent.com/88110335/183680943-9a0edfe9-8fa9-473f-835a-de78131346b2.png">

**Comment by krivard** [comment]
NCHS is supposed to publish on Mondays and Thursdays. This past Monday, it decided not to publish for some reason:
```
{"event": "No files were published today", "logger": "delphi_nchs_mortality.run", "level": "info", "timestamp": "2022-09-05T16:59:26.092003Z"}
```

Probably something amiss in the weekday logic.
