### ISSUE TITLE
Tag final version of safegraph-patterns indicator and remove from repo

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#1688]
The safegraph-patterns indicator was deactivated on July 15, 2022. We should 
- [x] tag the repo, so we can easily fetch the indicator code if we ever need it later
- [x] remove the indicator code, to keep a clean root directory for onboarding and crossboarding

**Comment by minhkhul** [comment]
Tag of Final archival version of safegraph_patterns:
https://github.com/cmu-delphi/covidcast-indicators/releases/tag/final-safegraph-patterns
