### ISSUE TITLE
Document whether our cases and deaths signals are by date of report or by date of case/death

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#178]
See this blog post: https://covidtracking.com/blog/is-there-a-right-way-to-chart-covid-19-deaths-over-time

I suspect our signals are by date of report, since they don't have the enormous backfill demonstrated in that article. But we should be sure, and we should add this to the documentation for each source. The docs should both specify what date applies (report date or actual death date) and, if it's indeed report date, explain that these values are subject to lag.

**Comment by krivard** [comment]
This is a reasonable flavor combo of "get familiar with COVIDcast data streams" and "get familiar with the API documentation" task: 
- [ ] Determine which definition is used by JHU, at the source
- [ ] Determine which definition is used by USAFacts, at the source
- [ ] Submit a PR to update the [JHU documentation](https://github.com/cmu-delphi/delphi-epidata/blob/main/docs/api/covidcast-signals/jhu-csse.md) and [USAFacts documentation](https://github.com/cmu-delphi/delphi-epidata/blob/main/docs/api/covidcast-signals/usa-facts.md) accordingly

**Comment by RoniRos** [comment]
Both JHU and USAFacts scrape the data from PH dept web sites, without elaborating on this issue.
The only such websites I have seen (e.g. Allegheny County) are always by date of reporting, but it's worth checking a larger random sample.
