### ISSUE TITLE
Examine Facebook survey for possible new sensors

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#18]
This paper says loss of smell or taste are excellent predictors; we should make a sensor out of the data we're getting from the facebook survey on that (`B2==13`)

* https://www.nytimes.com/2020/05/11/health/coronavirus-symptoms-app.html?referringSource=articleShare
* https://www.nature.com/articles/s41591-020-0916-2

**Comment by capnrefsmmat** [comment]
I'm going to split this into separate issues for the remaining indicators, and close this issue.
