### ISSUE TITLE
`value` in `covidcast-hospital-admissions-smoothed_covid19_from_claims` should not exceeds one?

### ISSUE THREAD

**Issue by caifand** [cmu-delphi/covidcast-indicators#1880]
**Actual Behavior:**

Hi, I have downloaded the hospital admissions data estimated from health insurance claims via the COVIDcast data exporter for all time span available. I've found that the `value` field — the estimated hospital admission percentage — is far larger than 1 when I look at different MSAs.

**Expected behavior**

I read the COVIDcast documentation online, especially the part about how the hospital admission percentage is estimated (see [here](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/hospital-admissions.html)). Based on my understanding, I expect this value never exceeds one because it describes a fraction of the total number of hospital admissions that COVID-19 hospital admissions take. So I wonder if it's correctly computed or if there's anything I've missed.

**Context**
I've provided where I've got the data and the part it refers to (by pointing to the specific link of the data documentation) above. So I currently cannot think of anything about the context to add. If there's anything unclear, could you please let me know?

Thank you very much for your work.

**Comment by nolangormley** [comment]
![image](https://github.com/cmu-delphi/covidcast-indicators/assets/6481154/af7eec30-88cd-45e1-be77-dc78ac8b6bff)
 Looking at the min/max values in the database I would say that it's likely percentage*100. Let me check with the team to ensure.

**Comment by caifand** [comment]
> Yup, per the [documentation](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/hospital-admissions.html) it seems that all estimations are multiplied by 100!

Yes, I did not understand that part initially. Thank you for your great and timely help!

**Comment by nolangormley** [comment]
Of course!

Just as a quick follow up, I checked with the team and there is not a standard within COVIDcast to show decimals or whole numbers for percentages and like numerics at the moment. One thing that can be very helpful in this case would be to check the metadata that comes along with a COVIDcast call. This will show you the min/max of the signal and give you a better idea.

We're always happy to help out though!
