### ISSUE TITLE
Validator not working for sources with weekly data

### ISSUE THREAD

**Issue by aysim319** [cmu-delphi/covidcast-indicators#2006]
**Actual Behavior:**

When running validator for sources with weekly data (nssp, nchs_mortality) the validator fails with the error: no files found

{"data_source": "nssp", "checks_run": 1, "checks_failed": 1, "checks_suppressed": 0, "warnings": 0, "phase": "validation", "elapsed_time_in_seconds": 0.01, "event": "Validation run successful", "logger": "_delphi_utils_python.delphi_utils.validator.run", "level": "info", "pid": 38146, "timestamp": "2024-07-29T21:03:01.034224Z"}
{"phase": "validation", "error_name": "check_empty_filelist", "signal": null, "resolution": null, "date": "*", "event": "check_empty_filelist failed for None at resolution None on *: No files found in export directory", "logger": "_delphi_utils_python.delphi_utils.validator.run", "level": "critical", "pid": 38146, "timestamp": "2024-07-29T21:03:01.034333Z"}

**Expected behavior**
Should find files

**Context**
the validator was specifically written for validating daily data specifically.

**Comment by nmdefries** [comment]
See https://github.com/cmu-delphi/covidcast-indicators/issues/1117
