### ISSUE TITLE
patch doctor visit issue date 20240731 and nchs issue date 20240801

### ISSUE THREAD

**Issue by minhkhul** [cmu-delphi/covidcast-indicators#2012]
[context here](https://delphi-org.slack.com/archives/C01LZ3A2UMU/p1722531121666209?thread_ts=1722470848.848359&cid=C01LZ3A2UMU).
issue date: July 31 2024
Data put under /common/covidcast/patch_doctor_visits_20240731 on prod.

**Comment by minhkhul** [comment]
related to [#2013](https://github.com/cmu-delphi/covidcast-indicators/issues/2013)

**Comment by minhkhul** [comment]
Add [this one](https://cronicle-prod-01.delphi.cmu.edu/#JobDetails?id=jlzbp9qjyaw) to the pile for related rsync change.

**Comment by minhkhul** [comment]
All files in batch issue format now saved on prod's `common/covidcast/patch_doctor_visits_20240731`. Just need to be moved to `common/covidcast/batch_issue_upload`and schedule run, possibly tomorrow night after google symptom big patch.

**Comment by melange396** [comment]
> Add [this one](https://cronicle-prod-01.delphi.cmu.edu/#JobDetails?id=jlzbp9qjyaw) to the pile for related rsync hiccup. Note: nchs time type is weekly.

this doesnt look like it has the same root cause; the other error was when rsync had files moved out from under it, this one looks like a bad variable replacement in the run script??
`rsync: link_stat "/common/covidcast/receiving/{acq_ind_name}" failed: No such file or directory (2)`

**Comment by minhkhul** [comment]
Patched!
Acquisition log: `/var/log/filebeat-pickup/epidata.acquisition.covidcast.csv_to_database_batch-issue-upload-2024-08-02T09_13_22Z.log`
Some api queries: 
`https://api.delphi.cmu.edu/epidata/covidcast/?signal=nchs-mortality:*&time=week:*&geo=state:*&issues=202431`
`https://api.delphi.cmu.edu/epidata/covidcast/?signal=doctor-visits:*&time=day:*&geo=county:*&api_key=ff62485cae8fc&issues=20240731`
