### ISSUE TITLE
Invalid classifier string breaks delphi_utils PyPI upload

### ISSUE THREAD

**Issue by melange396** [cmu-delphi/covidcast-indicators#2054]
Between 
* https://github.com/cmu-delphi/covidcast-indicators/pull/2052

and
* https://github.com/cmu-delphi/covidcast-indicators/pull/2053

...we got a [failure](https://github.com/cmu-delphi/covidcast-indicators/actions/runs/10838050925/job/30075433337#step:9:26) in the GH action that publishes the delphi_utils package, saying: "`'License :: MIT' is not a valid classifier.`"

The accepted version of this would be `License :: OSI Approved :: MIT License` according to [https://pypi.org/classifiers/](https://pypi.org/classifiers/#:~:text=License%20%3A%3A%20OSI%20Approved%20%3A%3A%20MIT%20License).  The other classifier strings we use appear to be valid.

Fix it in https://github.com/cmu-delphi/covidcast-indicators/blob/0da7b9aaa8715bab81d7023d48faa787f0c82851/_delphi_utils_python/pyproject.toml#L16 and https://github.com/cmu-delphi/covidcast-indicators/blob/0da7b9aaa8715bab81d7023d48faa787f0c82851/_template_python/pyproject.toml#L16

**Comment by dshemetov** [comment]
For future reference, [`validate-pyproject`](https://pypi.org/project/validate-pyproject/) could help catch issues like this in the future:

```sh
$ uv tool install 'validate-pyproject[all]'
Resolved 4 packages in 134ms
Prepared 3 packages in 49ms
Installed 4 packages in 5ms
 + fastjsonschema==2.20.0
 + packaging==24.1
 + trove-classifiers==2024.9.12
 + validate-pyproject==0.19
Installed 1 executable: validate-pyproject

# Running on _delphi_utils
$ uv tool run validate-pyproject pyproject.toml 
Invalid file: pyproject.toml
[ERROR] `project.classifiers[3]` must be trove-classifier

# After fix
$ uv tool run validate-pyproject pyproject.toml
Valid file: pyproject.toml
```
