### ISSUE TITLE
JHU MSA has inf values in some _prop signals

### ISSUE THREAD

**Issue by jsharpna** [cmu-delphi/covidcast-indicators#227]
In receiving, for many msa level wip files with prop, there are inf values.  The cause is that the aggregation (which should be happening on 'population') yields some 0 populations, when run through GeoMapper.  Here is an example of some rows...
```geo_id,val,se,sample_size,val_stable,se_stable,sample_size_stable
10180,inf,,,1012.7696318559967,,
10380,inf,,,,,
10420,inf,,,556.8447266067241,,
10500,inf,,,2591.1270959864937,,
10540,inf,,,187.28468042142902,,
```

**Comment by dshemetov** [comment]
@krivard I tested for any `inf` msa values in the output of my local jhu from the `deploy_jhu` branch and found none, so this seems fixed.

**Comment by chinandrew** [comment]
> @krivard I tested for any `inf` msa values in the output of my local jhu from the `deploy_jhu` branch and found none, so this seems fixed.

closing given this comment.
