### ISSUE TITLE
Geo refactor for Quidel covidtests

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#253]
GeoMapping related work after talking to Dmitry:
- [x] refactor the `geo_map.py` to make the steps for `msa/hrr_to_parent_state` independent from traditional geo mapping
- [x] jingjing will talk with Roni next Friday about whether to stick with geographical pooling (considering parent states).

_Originally posted by @jingjtang in https://github.com/cmu-delphi/covidcast-indicators/pull/193#issuecomment-683091316_

**Comment by krivard** [comment]
Geo refactor merged!

**Comment by jingjtang** [comment]
The code for switching to geo_map utils is ready, but problem encountered when running the unit tests. The unit test failed for a simple data frame which have integer values at zipcode level but float numbers after using the functions in geo utils to aggregate it from zipcode level to msa level. Will talk to @dshemetov first. If there does exist a problem in the utils, it will affect other signals that start from zip as well.

**Comment by jingjtang** [comment]
> The code for switching to geo_map utils is ready, but problem encountered when running the unit tests. The unit test failed for a simple data frame which have integer values at zipcode level but float numbers after using the functions in geo utils to aggregate it from zipcode level to msa level. Will talk to @dshemetov first. If there does exist a problem in the utils, it will affect other signals that start from zip as well.

Talked to Dmitry already. This is not a problem in the geo utils. But switching to geo utils from the traditional version does affect the results to be reported. @krivard We need to decide a time point to re-upload all of the reports dating back to late May.

**Comment by krivard** [comment]
Let's try for uploading tomorrow afternoon. The meta cache update will push ingestion to tomorrow evening, and if there's anything to debug we can catch it in the morning.

**Comment by chinandrew** [comment]
Is this resolved?

**Comment by krivard** [comment]
Yep! 🧹
