### ISSUE TITLE
Add 7-day average versions of SafeGraph signals

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#271]
Larry says forecasting has been using something similar, and they're extremely useful.

**Comment by sgsmob** [comment]
How are this and #273 supposed to be inserted?  It looks to me like

- Each input file corresponds to a single date.
- Each output file corresponds to a single input.
- The files are all processed independently in parallel.

Am I missing something or does this require a completely new paradigm where many/all input files are read simultaneously to pull out the data from the last n days?

**Comment by sgsmob** [comment]
What is the naming conventions for the files in this directory?  And is there a 1:1 correspondence between dates and input files?

**Comment by krivard** [comment]
The format for output files (which go into the `receiving` directory) is documented [here](https://github.com/cmu-delphi/delphi-epidata/blob/main/src/acquisition/covidcast/data_dir_readme.md).

The naming convention for input files (which are pulled from `s3://sg-c19-response/social-distancing/v2/` and saved into the `{raw_data_dir}/social-distancing/` directory is apparently undocumented -- we should fix that; it would go into DETAILS.md or a line comment [here](https://github.com/cmu-delphi/covidcast-indicators/blob/8678fba21fbf2d30390ebb49ec1141fc96411fbf/safegraph/delphi_safegraph/run.py#L48). Digging it out of the server, I get `{raw_data_dir}/social-distancing/{YYYY}/{MM}/{DD}/{YYYY}-{MM}-{DD}-social-distancing.csv.gz`
