### ISSUE TITLE
Resolve Jenkins linter regression problem in JHU

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#275]
#272 failed to check due to a regression in astroid, a component of pylint. This appears to only be a problem for certain version combinations of python, pylint, and pandas. We have temporarily disabled linting in the JHU indicator (#274), but that's not a good long-term solution.

Figure out what's up, decide how to fix it, and repair the Jenkins job for JHU.

**Comment by chinandrew** [comment]
This was fixed in #333
