### ISSUE TITLE
Implement reidentification protection for symptom survey individual response data

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#281]
**Actual Behavior:**

The symptom survey individual response data currently does not include race and ethnicity, because of the risk of reidentification of respondents. This means scientific partners do not receive this data.

**Expected behavior**

We should implement some kind of reidentification protection so that we can release this data and enable work by our scientific partners, but with lower risk of reidentification. This might involve data swapping, differential privacy, or some other approach (like simply omitting the data in areas where reidentification risk is high because of low sample size).

If we can't identify an acceptable strategy, we should solicit input from survey users to understand what they want to know about race and ethnicity, and generate new aggregate cross-tabs (see #129) that support this.

**Context**

Facebook's privacy team requested that we do this before allowing us to release the data to data users, and so our approach must be run past them before it's implemented. See the [brief description we provided them](https://docs.google.com/document/d/1PyBbew-WHEatFDR6_dKTw8KoAMunKgkppNkyg1x7Zsk/edit?usp=sharing) while finalizing the new survey wave.

**Comment by dshemetov** [comment]
The differential privacy design for this problem has come to a few key points:
1. How do we choose epsilon? (a key parameter that controls the amount of privacy given by increasing the amount of noise added)
2. How do we assist users in making corrections to the data, given a noising policy?
3. How do we deal with binning the combination of Hispanic/Non-Hispanic and race questions, especially given that the Census Bureau does not provide distributions for some of these categories?

Current thoughts:
1. A [recent (2019)](https://journalprivacyconfidentiality.org/index.php/jpc/article/view/689) review of epsilon choice in industry has narrowed it down to the range [0.1 , 4]. Choices in this range can be guided by our understanding of the effects of noising on user's data analysis, which we don't understand well yet (Amin may have something for us by Monday).
2. Our best lead here is [Jan Selén 1986] and what Amin comes up with.
3. Two of our options are: we bin in a way where we can make Census-based resampling or we resample in an ad-hoc manner (uniform distribution or using national demographics).

**Comment by chinandrew** [comment]
I would add for (3) that this is particularly tricky for multiple races.

**Comment by dshemetov** [comment]
Another component to the decision making here is that multiple releases of the data with different noisings degrade the privacy guarantee. One way to think about it is that each release is additive in epsilon, so two releases of the data with the same epsilon results in an effective epsilon of 2*epsilon. This factor means that we should: anticipate this and choose epsilon/n, where n is our number of expected re-releases, and minimize n.

**Comment by capnrefsmmat** [comment]
Race/ethnicity data is now available to qualifying data users under a different scheme.
