### ISSUE TITLE
Develop infra for replacing "wip" method of staging prototype public signals

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#290]
We currently prototype public signals by slapping 'wip_' on the front of the signal name and having the API server filter those results out of the metadata. The WIP mechanism was a necessary evil for quickly giving us a way to preview prototypes in the map, but it's also obnoxious and error-prone:
* The person who develops the signal has to have SSH access to the primary Delphi server, or hand off files to someone who does
* Without metadata, you have to compute the mean and stdev for each region manually when configuring the map preview
* Once the prototype is approved, you have to apply the signal name change to the indicator code, in the public database, and in the map config file, which all have the possibility for error

We happen to have a staging server already set up, so @korlaxxalrok is working on a way to use that for prototypes instead.

**Comment by korlaxxalrok** [comment]
@krivard I think enough of this is in place that we can consider using it.

The primary goal is complete: A mechanism to aid in proxyingy to different endpoints based on prototype/non-prototype query type.

A good near term follow on should be more specific access control, but we can move forward for now.

**Comment by krivard** [comment]
Excellent. To test the whole shebang, I believe this is sufficient:

1. generate a branch of `www-covidcast` from `sgratzl/configure_endpoint`
2. configure the preview URL to point to the new proxy
3. add one of the staging-only signals to `src/stores/constants.js`
4. create a PR
5. view preview
