### ISSUE TITLE
"Apparent" missingness in GHT

### ISSUE THREAD

**Issue by huisaddison** [cmu-delphi/covidcast-indicators#292]
**Actual Behavior:**

"Apparent" missingness: for most days, what appears to be missing data is actually a 0 in the GHT indicator.  (There is the meta-issue regarding whether a 0 should be interpreted as a signal that indicates a low, but nonzero volume of searchers, or whether it should be interpreted as actual missing data).  The map renders an exact zero as a solid gray (rather than a diagonally hatched gray, which indicates true missingness as a matter of fact about what's in our API).  To me, the pipeline is working properly, and the discussion should be whether anosmia and i' can't smell or taste now has low recall and therefore we should adjust the terms in our bag. 

**Expected behavior**

Should we change our bag of terms to something with higher recall now that it's no longer March, and people's search habits have changed?

**Context**

https://delphi-org.slack.com/archives/C0130CSQRN3/p1601495049023500?thread_ts=1601480482.022300&cid=C0130CSQRN3

cc @ryantibs who pointed this out originally
cc @nmdefries who is working on Google Symptoms, which may replace GHT
cc @jingjtang who is the current pipeline "maintainer" to my knowledge

**Comment by nmdefries** [comment]
GHT has been deprecated (on the Google side) and replaced by Google Symptoms, which we expect to be more robust to shifts in specific search terms used.
