### ISSUE TITLE
Adapt pipeline automation to use archive module

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#302]
Now that we have a mechanism for running the diff archiver as a separate pipeline step, #295, we should fix the automated pipelines to actually use it that way.

The indicators that currently use the archive differ internally will have to be modified in favor of this alternate approach. This could be done as separate PRs that then get propagated to `main`, or as one combined PR to `main` that then gets propagated to the deployment branches. I have a slight preference for the former since that way we don't end up with surprises in the CI/CD system.

- [ ] Drop archiving from JHU internal pipeline
- [ ] Drop archiving from USAFacts internal pipeline
- [ ] Drop archiving from google_health internal pipeline
- [ ] Drop archiving from EMR internal pipeline (currently deactivated, but no reason to leave dead code around in case we get the EMR data source back)

@korlaxxalrok to draw up a list of additional requirements on the server side, including who has the power to complete each step.

**Comment by korlaxxalrok** [comment]
@krivard Server side we'd probably create a flow with two steps: one for the indicator and one for the archiver. We'd need one flow per indicator, and then we'd replace the currently scheduled indicator job with the new flow. After some basic testing this should be pretty straight forward to set up.

As far as who can do this, anyone with the ability to manipulate Automation should be able to perform these steps.
