### ISSUE TITLE
national US level data not available from jhu-csse signal

### ISSUE THREAD

**Issue by nickreich** [cmu-delphi/covidcast-indicators#303]
**Actual Behavior:**

According to the covidcast geography page, there is not a US national level source. https://cmu-delphi.github.io/delphi-epidata/api/covidcast_geography.html

But this is data that is available from JHU.

**Expected behavior**

I would like to be able to download national level counts from JHU by specifying say `geo_type` = 'national' and/or `geo_value`='us'

**Comment by capnrefsmmat** [comment]
We're tracking adding a national level to all signals in #199.

**Comment by nickreich** [comment]
Sounds good. And I understand that this may require additional computation for other signals, but just to be clear that this is a data signal that is already in the JHU CSSE raw data, so once the decision about how to geocode national levels is made, this data could be added. We are trying to migrate our systems over to using covidcast, but not having the national level signal is going to significantly hamper our ability to make this switch.

**Comment by nickreich** [comment]
I've been informed that the above statement (that national signal is already in csse raw data) is not true.

**Comment by nickreich** [comment]
Again, related to my comment over at https://github.com/cmu-delphi/covidcast-indicators/issues/23
I want to mention that this is another impediment to us at the Hub switching over to using covidcast. Again, we have built our own version of this, but really really want to rely on covidcast for this!
