### ISSUE TITLE
Add DMA support for geomapping utilities

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast-indicators#312]
Currently the geomapper doesn't handle DMAs. This will be needed eventually for Google Health, which has its own methods to aggregate DMA regions to HRR and MSA regions.

**Comment by dshemetov** [comment]
Ah, I guess I wasn't aware. So the finest geo resolution for Google Trends is DMA?

**Comment by chinandrew** [comment]
Sorry I meant google health, not trends. Is that one deprecated like you mentioned in the other issue?

**Comment by krivard** [comment]
Google Health Trends = GHT = Google Health = Google Trends = Search Trends = the old indicator, soon to be retired.

The terminology we're sticking to for the new search terms indicator is Google Symptoms.

**Comment by krivard** [comment]
wontfix, in favor of the new Google Symptoms indicator coming up soon ([relevant note from Nat](https://github.com/cmu-delphi/covidcast-indicators/issues/306#issuecomment-709490553))
