### ISSUE TITLE
Release 7-day average signals for Safegraph

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#332]
- [Link to issue](https://github.com/cmu-delphi/covidcast-indicators/issues/271)
- [Link to PR](https://github.com/cmu-delphi/covidcast-indicators/pull/309)
- Proposed release version: 1.11

This work creates 7-day average signals for each of the following:

* median_home_dwell_time
* completely_home_prop
* full_time_work_prop
* part_time_work_prop

- [x] write API [documentation](https://github.com/cmu-delphi/delphi-epidata/tree/main/docs/api) and/or [changelog](https://github.com/cmu-delphi/delphi-epidata/blob/main/docs/api/covidcast_changelog.md)
- [x] write API mailing list notification

- [x] Statistical review (usually [correlations](https://github.com/cmu-delphi/covidcast/tree/main/docs/R-notebooks))
- [x] Signal / source name review (usually [Roni](https://docs.google.com/document/d/10hGd4Evce4lJ4VkWaQEKFQxvmw2P4xyYGtIAWF52Sf8/edit?usp=sharing))

- [x] Visual review
- [x] write [Signal description pop-up text](https://docs.google.com/document/d/1RLy4O-gtACVjLEVD_vxyPqvp9nWVhqEjoWAKi68RKpg/edit#heading=h.oxebzdy7nl8w) & review
- [x] ~write [Map release notes](https://docs.google.com/document/d/1BpxGgIma_Lkd2kxtwEo2DBdHQ3zk6dHRz-leUIRlOIA/edit?usp=sharing)~ (I think we're not doing these by hand any more?)

**Comment by benjaminysmith** [comment]
Hi @sgsmob, take a look at https://github.com/cmu-delphi/covidcast-indicators/issues/367 for an example of what we need for the initial steps.

**Comment by sgsmob** [comment]
Documentation update PR here:  https://github.com/cmu-delphi/delphi-epidata/pull/275

**Comment by sgsmob** [comment]
Draft mailing list notification:

Hi COVIDcast API users,

We are pleased to announce the availability of smoothed versions of existing signals
based on SafeGraph mobility data.

Each of the following signals previously available now has a corresponding additional 7-day trailing average signal, i.e., the reported value for May 10 is the average of values from May 4 - May 10:

1. Proportion of people at home for the whole day
2. Proportion of people working full time outside the home
3. Proportion of people working part time outside the home
4. Median number of hours spent at home

The signal names and technical details for each of these signals
are provided in our API documentation:
https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/safegraph.html

**Comment by sgsmob** [comment]
Correlation plots for the smoothed signals look alright to me, although somewhat concerning that they are becoming less indicative recently.

![smoothed_correlations](https://user-images.githubusercontent.com/5510365/98691030-98e32e00-233b-11eb-9d6b-8504d3efbb09.png)

**Comment by sgsmob** [comment]
Compared to the existing raw signals, the averaged signals look more useful/interpretable:

![raw_correlations](https://user-images.githubusercontent.com/5510365/98691171-c039fb00-233b-11eb-9c5e-946c3a96c1e2.png)

**Comment by krivard** [comment]
@sgsmob the additional unsmoothed correlations plot is helpful here, since it shows the same degradation in correlations over the past four weeks -- thanks for including it.

The decline is worrisome, and it's possible we might want to pause or even retire these signals (both raw and 7dav). I've put it on the agenda for Thursday's team leads.

**Comment by capnrefsmmat** [comment]
If I had to make a wild guess, I'd say the decline in correlation is because cases are now exponentially growing *everywhere*, and slightly lower mobility is no longer enough to prevent spread. But that's a wild guess.

I think the signals still are useful for research even if they don't correlate with case rates; for example, researchers studying the effects of social distancing orders, compliance with them, the economy, or mental health could all find these signals useful for their work.

**Comment by benjaminysmith** [comment]
Result of team leads was that we are going to keep the signals around, so this is unblocked.

**Comment by benjaminysmith** [comment]
@krivard for visual review it looks like the averages match the raw data. Seems reasonable to me. What do you think?

@sgsmob are the signal names in https://docs.google.com/document/d/10hGd4Evce4lJ4VkWaQEKFQxvmw2P4xyYGtIAWF52Sf8/edit#heading=h.vu3vsc11yl09 correct? If so, lets ask for Roni approval.

**Comment by sgsmob** [comment]
Yes, they are correct

**Comment by benjaminysmith** [comment]
@RoniRos can you please review the names [here](https://docs.google.com/document/d/10hGd4Evce4lJ4VkWaQEKFQxvmw2P4xyYGtIAWF52Sf8/edit#heading=h.vu3vsc11yl09)?

**Comment by krivard** [comment]
For visual review @sgsmob can you drop a map display in thread? Whatever default settings the clients have built in is fine.

**Comment by sgsmob** [comment]
@krivard I have a notebook with slider maps in it but I don't know if you are looking for something different here.

**Comment by krivard** [comment]
That sounds fine?

**Comment by sgsmob** [comment]
What is the best way to share a notebook?  Should I commit it to a repo and link it from here?  Save the html and upload it?  Drive link?

**Comment by krivard** [comment]
Upload the HTML or drive link

**Comment by sgsmob** [comment]
https://drive.google.com/file/d/1P26xetIoby7k_UMkeI0FFZf6LL3Ur7Zd/view?usp=sharing

**Comment by sgsmob** [comment]
Something seems wrong with the median computation.  I am going to take a look at that some more.

**Comment by sgsmob** [comment]
> Something seems wrong with the median computation. I am going to take a look at that some more.

Thought this was in hours, but it is actually in minutes; no problem here.

**Comment by RoniRos** [comment]
>  [ ]  write [Signal description pop-up text](https://docs.google.com/document/d/1kDqRg8EaI4WQXMaUUbbCGPlsUqEql8kgXCNt6AvMA9I/edit?usp=sharing) review

@krivard, I think this linked to the deprecated version.  I think [this ](https://docs.google.com/document/d/1RLy4O-gtACVjLEVD_vxyPqvp9nWVhqEjoWAKi68RKpg/edit#heading=h.oxebzdy7nl8w
)is the correct link.

**Comment by sgsmob** [comment]
Sample pop-up text:

Name: Away from Home 6hr+ a Day (smoothed)
Id: safegraph
Signal: full_time_work_prop_7dav
Type: public
Levels: [county, state]
YAxis: Proportion
Format: raw
HasStdErr: true

MapTitleText: 7-day trailing average of fraction of people spending 6 hours or more between 8am-6pm, in one location away from their home, based on SafeGraph mobility data

Description: Delphi receives data from [SafeGraph](https://docs.safegraph.com/docs/social-distancing-metrics), which collects anonymized location data from mobile phones. Using this data, we calculate the fraction of mobile devices that spent more than 6 hours at a location other than their home during the daytime and average it over a 7 day trailing window. This indicator measures how mobile people are, and ought to reflect whether people are traveling to work or school outside their homes. See also our Away from Home 3-6hr indicator.

Links:
[Technical description](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/safegraph.html)

---

Name: Away from Home 3-6hr a Day (smoothed)
Id: safegraph
Signal: part_time_work_prop_7dav
Type: public
Levels: [county, state]
YAxis: Proportion
Format: raw
HasStdErr: true

MapTitleText: 7-day trailing average of fraction of people spending 3-6 hours between 8am-6pm, in one location away from their home, based on SafeGraph mobility data

Description: Delphi receives data from [SafeGraph](https://docs.safegraph.com/docs/social-distancing-metrics), which collects anonymized location data from mobile phones. Using this data, we calculate the fraction of mobile devices that spent between 3 and 6 hours at a location other than their home during the daytime and average it over a 7 day trailing window. This indicator measures how mobile people are. See also our Away from Home 6hr+ indicator.

Credits: We are happy for you to use this data in products and publications under the terms of the Creative Commons Attribution license.

Links:
[Technical description](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/safegraph.html)

---

**Comment by krivard** [comment]
I've approved the API docs and transferred the proposed signal description text (with my modifications) into the auto doc. They'll get their final review during the map release candidate comment period; not sure whether to tick the box in this issue or not

**Comment by sgsmob** [comment]
Release notes:

Add 7-day averages of SafeGraph mobility signals

**Comment by RoniRos** [comment]
@krivard I did not see any comments on, or acceptance/rejection of, my proposed edit from "Away from Home 3-6hr a Day" to "At Away Location 3-6hr", and similarly for 6hr+.  Did you mean to reject it?  To me, "Away from home X hours" is a mischaracterization, but I can understand if some might prefer to keep a simpler description even if not completely accurate. 

Similarly for my suggestion for the Y Axis label to be "Fraction of population" -- I think it's more informative.

**Comment by krivard** [comment]
@RoniRos I think you're looking for [the frontend thread about misleading labeling](https://github.com/cmu-delphi/www-covidcast/issues/606#issuecomment-728286463) (I approve of your changes; we're just waiting on Alex) -- this thread is instead about adding language for the switch to the smoothed signals.

**Comment by krivard** [comment]
Calling this good
