### ISSUE TITLE
Pylint/Astroid gives "RecursionError: maximum recursion depth exceeded" in CI tests

### ISSUE THREAD

**Issue by benjaminysmith** [cmu-delphi/covidcast-indicators#333]
Recent discussion in PR review: https://github.com/cmu-delphi/covidcast-indicators/pull/314#issuecomment-712877800

Example of error: https://jenkins-ci-prod-01.delphi.cmu.edu/blue/organizations/jenkins/covidcast-indicators/detail/PR-314/3/pipeline/

Discussion on previous PR: https://github.com/cmu-delphi/covidcast-indicators/pull/272#issuecomment-691215885

**Comment by chinandrew** [comment]
Looks to be an open issue https://github.com/PyCQA/pylint/issues/3836. Been banging my head on this for a while to no avail, including upgrading astroid directly from their github, trying to align package versions, and changing the python version. 

I've been able to reproduce this by pulling the `pip list` from the CI and intsalling those locally, so going to try to narrow down the suspect packages.

**Comment by chinandrew** [comment]
This appears to be due to pandas _and_ the ubuntu version. Locally downgrading to 1.1.1 makes things works, 1.1.2 or above breaks it. However when I pin this on the CI it didn't work :/. The `pip list`s locally and on CI were identical. So then I learned `ubuntu-latest` on Github Actions is ubuntu 18.04, not 20.04 which is what I'm running. Upgraded that and now things are working. @korlaxxalrok FYI

**Comment by sgsmob** [comment]
It looks like `df = pd.merge(df, other)` is a common cause of this problem and replacing it with the equivalent `df = df.merge(other)`.  Going through and seeing if this is sufficient to at least stop the issue in the near-term.

**Comment by chinandrew** [comment]
> It looks like `df = pd.merge(df, other)` is a common cause of this problem and replacing it with the equivalent `df = df.merge(other)` removes the error. Going through and seeing if this is sufficient to at least stop the issue in the near-term.

That's interesting, thanks for looking into it :+1:

**Comment by chinandrew** [comment]
As another confusing data point, I just hit this error on the covidcast repo where the linter didn't complain on a pd.merge(x,y), but then complained when i moved that line into a new file..... :angry:
