### ISSUE TITLE
Resurrect a measure of signal trend

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/covidcast-indicators#381]
We used to have a "Trend" button, which for a given signal showed whether it was increasing, decreasing or stable in each location.  We disabled it because it was hard to get a consistent definition.  I think we should resurrect some version of it, because it is otherwise hard to find locations (say, counties) with rapid rise.  The only current alternative is to watch a time lapse and try to "catch" locations whose color changes fast, but that's super suboptimal.

An alternative would be to add an option to "Top 10" for "fastest changing".  But this still requires some definition of change (e.g. window over which the change is measured), and once we have this definition, we might as well use it to resurrect the "Trend" button.

**Comment by krivard** [comment]
We decided not to include trend in the API, but instead to estimate derivative and classify trend in the clients. Once that work is complete, we can pursue including it in a map release.

Blocked on cmu-delphi/covidcast#131.

**Comment by RoniRos** [comment]
@krivard We can try to finesse the derivative issue by using the "top 10" mechanism rather then the "Trend" button.  Rather than having to decide on a threshold or even on statistical significance, we can just sort by steepness of change (it does require a choice of window size though).  It will be far from perfect, but the top K will be meaningful, for K=10 or even 100.  Better an imperfect tool than none at all.
