### ISSUE TITLE
Remove deprecated google health indicator directory

### ISSUE THREAD

**Issue by chinandrew** [cmu-delphi/covidcast-indicators#395]
Blocked by #270 

google_health is deprecated, but is still in production while we work on the new GS indicator.

**Comment by chinandrew** [comment]
Now that google symptoms is released in #577, is this unblocked? Are there any additional steps that need to be taken to remove from production?

@krivard

**Comment by krivard** [comment]
Not unblocked until the public release tomorrow morning. After that, we should
- [ ] Let GHT and GS run simultaneously for a week, to shake out any obvious badness with GS
- [ ] Disable GHT in Delphi Automation, announce GHT's retirement to the mailing list, and move GHT to the list of Retired Signals in the API docs
- [ ] Wait a week for cries of distress
- [ ] Remove all dead code from this repository and ~indicators on primary, as well as the dead Automation step
