### ISSUE TITLE
Add Safegraph "x to y minutes away from home" signals (for all-away-locations)

### ISSUE THREAD

**Issue by huisaddison** [cmu-delphi/covidcast-indicators#405]
Our current Safegraph mobility signals, which are ([misleadingly](https://github.com/cmu-delphi/www-covidcast/issues/606)) presented on the COVIDcast map as 3-6hr and 6hr+ away from home, actually carry the qualifiers "away from home in a single location, between the hours of 8am and 6pm local time).

We should weaken these assumptions.  We'll probably get some more interesting behavior from people who are out and about, but not necessarily "working".

**Data details**
 
Use [bucketed_away_from_home_time](https://docs.safegraph.com/docs/social-distancing-metrics) is JSON{string : integer} and maps minutes away from home to a count.  From the linked documentation:

> Key is range of minutes and value is device count of devices that dwelled anywhere outside of the geohash-7 of home for the given time period. For each device, we summed the observed minutes away from home across the day (whether or not these were contiguous) to get the total minutes for each device this day. Then we count how many devices are in each bucket. Beginning in v2, we include the portion of any stop within the time range regardless of whether the stop start time was in the time period.

**Additional context**

**Comment by RoniRos** [comment]
I strongly support this.  Many people's job is not tied to a single location (traveling salespeople, drivers, supervisors of multiple sites, farmers).

**Comment by RoniRos** [comment]
How about we offer a new "average time away from home" signal based on the above?  Arguably, individual risk is linear in the amount of time away from home.  Perhaps more accurately, it is linear in (time away from home) X (public's density at that time), so something like a quadratic.  So we may want to also release a signal that is the integral of squared "away from home" over a 24 hour period.  @huisaddison ?

**Comment by krivard** [comment]
Isn't that just 24*60 - [the `median_home_dwell_time` signal we already have](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/safegraph.html)?

**Comment by RoniRos** [comment]
Yes, other than the mean/median distinction.  I  am curious why median was chosen rather than mean.  But anyway, this may be close enough, especially since the value range is limited.

Re my proposed integrated squared mean:  we may want to refine it by considering the hourly density in specific POIs (regardless of the home of the phones).  @huisaddison if you are interested, let's talk!

**Comment by huisaddison** [comment]
@RoniRos I like the idea, and Safegraph provides more a more fine-grained view of how much time people (cell phones) are away from home via [`bucketed_away_from_home_time`](https://docs.safegraph.com/docs/social-distancing-metrics).  If the proposed signal is to implemented, perhaps @krivard can choose an appropriate person for the task?  (I must respectfully decline because my worktime is completely saturated in the [indicator heterogeneity DAP that grew out of the DV correlation analysis](https://github.com/cmu-delphi/covidcast-modeling/issues/18)).

**Comment by RoniRos** [comment]
@huisaddison Ok.  before any thought of implementation, this will require some careful design.  Given your familiarity with SafeGraph data, do you have the time and inclination to make a specific proposal which you and I can then discuss?  
You may be familiar with the basic equation of the SIR model (dI/dt = \beta * I * S).  Can you think of which of the available SafeGraph statistics we could use to to approximate this equation at the Census Block and/or POI levels?

**Comment by huisaddison** [comment]
I think that either @jingjtang or @sgsmob would be better suited for this -- I actually haven't touched the Safegraph code since June!  So both Jingjing and Mike are more familiar with the data at this point.

**Comment by sgsmob** [comment]
I have a lot on my plate and this would not get attention for a bit, but if it isn't that important I would happy to take it on.

**Comment by krivard** [comment]
SafeGraph has retired its pandemic mobility signals, so this project is no longer feasible.
