### ISSUE TITLE
ght `raw` is the same as `smoothed` since august

### ISSUE THREAD

**Issue by dfarrow0** [cmu-delphi/covidcast-indicators#410]
**Actual Behavior**

[The `raw` signal is equal to the `smoothed` signal](https://delphi.cmu.edu/epivis/epivis.html#eyJjaGFydCI6eyJ2aWV3cG9ydCI6WzczNzQzNC42OTcwMDMzODQsLTM3Ljc5NDc3NjU5Mzk3MTA0LDczNzc0Mi4zMDI5OTY2MTYsMTE2LjQwOTA0ODQ3MzEzOTA0XSwic2hvd1BvaW50cyI6ZmFsc2V9LCJkYXRhc2V0cyI6W3siY29sb3IiOiIjODlkN2FhIiwidGl0bGUiOiJ2YWx1ZSIsInBhcmVudFRpdGxlIjoiRGVscGhpIENPVklEY2FzdDogR0EgcmF3X3NlYXJjaCAoZ2h0KSIsInBhcmFtcyI6WyJjb3ZpZGNhc3QiLCJnaHQiLCJyYXdfc2VhcmNoIiwiZGF5Iiwic3RhdGUiLCJHQSJdfSx7ImNvbG9yIjoiIzlmNjQ3MCIsInRpdGxlIjoidmFsdWUiLCJwYXJlbnRUaXRsZSI6IkRlbHBoaSBDT1ZJRGNhc3Q6IEdBIHNtb290aGVkX3NlYXJjaCAoZ2h0KSIsInBhcmFtcyI6WyJjb3ZpZGNhc3QiLCJnaHQiLCJzbW9vdGhlZF9zZWFyY2giLCJkYXkiLCJzdGF0ZSIsIkdBIl19XX0=), starting in August.

**Expected behavior**

The raw signal is generally different than the smoothed signal.

**Context**

https://github.com/cmu-delphi/covidcast-indicators/tree/main/google_health

**Comment by dfarrow0** [comment]
By default, only data for a single day is pulled from the api: https://github.com/cmu-delphi/covidcast-indicators/blob/8a0a2c0e86adc30fb25dbc66dd5268b4f57d5fcf/google_health/delphi_google_health/run.py#L53-L61

And a 1-length timeseries results in a singular matrix, causing smoothing to fall back to the raw value: https://github.com/cmu-delphi/covidcast-indicators/blob/8a0a2c0e86adc30fb25dbc66dd5268b4f57d5fcf/google_health/delphi_google_health/smooth.py#L72-L74

**Comment by dfarrow0** [comment]
Some unorganized thoughts:

- my general advice is to avoid precomputing and storing a signal that's deterministically derived from another signal. recommendation is to serve the underlying signal and let callers do the computation on the fly. not saying that's always the best choice, as there are certainly tradeoffs to consider. buy my preference is to avoid precomputing unless there's a compelling reason otherwise.
- due to the bug in this issue, the `smoothed` signal is equal to the `raw` signal for many, many rows. once this all gets sorted out, we'll need to go back and recompute the `smoothed` signal so that the fix is applied retroactively to affected rows, and not just to new rows.
- an attribute of the smoother, which is a feature from a theoretical perspective but a drawback from a practical perspective, is that it has infinite support. meaning that the smoothing isn't done over a fixed window, but over the _entire history_ of the signal. using the full history is problematic because it requires fetching the whole time-series (either from GHT or from API or from cache), which adds cost and complexity. it would be simpler to just fetch, say, the last 10 days, and then smooth over a sliding window. unfortunately, that would lead to ever-so-slightly different values of `smoothed` for each of the 10 days that it's computed. which dirties the CSV cache on those days, and causes us to store not 2x the data, but _10x the data_. i.e. we would store the original `raw` signal, the `smoothed` signal that's `as_of` a day with 10 days of data, the `smoothed` signal that's `as_of` a day with 9 days of data, and so on.

do we have any idea of whether the `smoothed` signal is actively used? if it's not, i recommend just removing the smoothed signal from the api altogether.

**Comment by jingjtang** [comment]
The cache file used for automation is surprisingly differently from the ones generated locally. Coordinate with @korlaxxalrok to make sure whether this is a problem with cache files. Currently, if run locally, everything seems fine to me. The `smoothed_search` is different from `raw_search`, `test_smooth.py` passed. 

Other problems noticed with unit tests:
- Not a dry-run mode, `ght-key` is needed for `test_run.py`
- mocked or faked aws_credentials and bucket should be set up for `./tests/params.json` which is not there currently.
- `test_match_old_raw_output` and `test_match_old_smoothed_output` failed.
```
============================================ short test summary info ============================================
FAILED test_run.py::TestRunModule::test_match_old_raw_output - AssertionError: DataFrame.iloc[:, 1] (column na...
FAILED test_run.py::TestRunModule::test_match_old_smoothed_output - AssertionError: DataFrame.iloc[:, 1] (colu...
```

**Comment by jingjtang** [comment]
For some reason, the code for automation results in only one lines with the most recent data in all of the cache files. This is the reason why we get `smoothed_search` exactly the same as `raw_search`. This is different from what we should get from the code in `deploy-google_health` branch. Now, making further comparison between them.

**Comment by krivard** [comment]
GHT hitting the network during tests is a [known problem](https://github.com/cmu-delphi/covidcast-indicators/issues/213); it may be easier to fix that first and then address the cache problem>

**Comment by jingjtang** [comment]
@krivard A simple fix [here](https://github.com/cmu-delphi/covidcast-indicators/pull/423#issue-514444475). We can fix that problem with unit tests in another PR.

**Comment by dshemetov** [comment]
@dfarrow0 FWIW, I changed the support to a finite value (about a month) in the [refactored smoother utility](https://github.com/cmu-delphi/covidcast-indicators/blob/main/_delphi_utils_python/delphi_utils/smooth.py). Speed-wise the smoothing could move to the client side (smoothing a 1000-length signal takes ~3.5 ms), but I don't have a good sense of other involved dependencies.
