### ISSUE TITLE
Release Google Symptoms

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#438]
- [Link to issue](https://github.com/cmu-delphi/covidcast-indicators/issues/270#)
- [Link to PR](https://github.com/cmu-delphi/covidcast-indicators/pull/344)
- Proposed release version: 1.11

Remaining work:

- [x] Statistical review - @jingjtang and @nmdefries these probably already exist?
- [x] Visual review - use one of the covidcast client packages to do up some demo maps
- [x] Signal / source name review (usually [Roni](https://docs.google.com/document/d/10hGd4Evce4lJ4VkWaQEKFQxvmw2P4xyYGtIAWF52Sf8/edit?usp=sharing))
- [x] Add to Automation - @jingjtang and @korlaxxalrok 
- [x] API [documentation](https://github.com/cmu-delphi/delphi-epidata/tree/main/docs/api) and/or [changelog](https://github.com/cmu-delphi/delphi-epidata/blob/main/docs/api/covidcast_changelog.md) - @jingjtang and @Akvannortwick 
- [x] API mailing list notification - @Akvannortwick 
- [x] [Signal description pop-up text](https://docs.google.com/document/d/1kDqRg8EaI4WQXMaUUbbCGPlsUqEql8kgXCNt6AvMA9I/edit?usp=sharing) draft & review - @jingjtang and @Akvannortwick 
- [x] [Map release notes](https://docs.google.com/document/d/1BpxGgIma_Lkd2kxtwEo2DBdHQ3zk6dHRz-leUIRlOIA/edit?usp=sharing) - @Akvannortwick

**Comment by nmdefries** [comment]
Re: Statistical review

* Brief correlations analysis of individual symptoms (anosmia and ageusia) with cases: [code](https://github.com/cmu-delphi/covidcast-modeling/blob/google-symptoms-dap/google_symptoms_exploration/01_correlations_demo.Rmd), [output](https://github.com/cmu-delphi/covidcast-modeling/blob/google-symptoms-dap/google_symptoms_exploration/01_correlations_demo.html)
* In-depth correlations analysis of all symptoms with cases: [code](https://github.com/cmu-delphi/covidcast-modeling/blob/google-symptoms-dap/google_symptoms_exploration/02_comprehensive_correlations.Rmd), [output](https://github.com/cmu-delphi/covidcast-modeling/blob/google-symptoms-dap/google_symptoms_exploration/02_comprehensive_correlations.html)
* Comparison of anosmia and ageusia with GHT indicator. Simple forecasting problem demonstrating predictive power: [code](https://github.com/cmu-delphi/covidcast-modeling/blob/google-symptoms-dap/google_symptoms_exploration/03_compare_gs_ght.Rmd), [output](https://github.com/cmu-delphi/covidcast-modeling/blob/google-symptoms-dap/google_symptoms_exploration/03_compare_gs_ght.html)

**Comment by jingjtang** [comment]
Hi @korlaxxalrok, this is the third pipeline that needs to be automated.

**Comment by jingjtang** [comment]
A simple state level visual view [here](https://drive.google.com/file/d/1rg0ethbpmCt0fLSUZrsuJuKBgs_tAr3S/view?usp=sharing)

**Comment by jingjtang** [comment]
Correlating usa-facts: confirmed_7dav_incidence_prop averaged from 2020-10-17 to 2020-10-20 against google-symptoms signals from 2020-10-10 to 2020-10-13

- State Level (very good geo-wise correlation)
![state_ageusia](https://user-images.githubusercontent.com/31444565/98485625-c5853180-21e5-11eb-95b5-ddc4d16ea5d2.png)
![state_anosmia](https://user-images.githubusercontent.com/31444565/98485627-c61dc800-21e5-11eb-8518-6fb3ec2f15d0.png)
![state_combined](https://user-images.githubusercontent.com/31444565/98485629-c61dc800-21e5-11eb-8488-32c4b592cdfc.png)

- MSA Level (bad; probably because we do not have a good coverage)
![msa_ageusia](https://user-images.githubusercontent.com/31444565/98485641-dafa5b80-21e5-11eb-8e8f-e5b569829ef7.png)
![msa_anosmia](https://user-images.githubusercontent.com/31444565/98485642-dafa5b80-21e5-11eb-9efb-5fcbeeac2b7c.png)
![msa_combined](https://user-images.githubusercontent.com/31444565/98485643-dafa5b80-21e5-11eb-81dd-127c452d1a29.png)

- County Level: not available, too low geo coverage

**Comment by jingjtang** [comment]
A draft PR for API documentation [here](https://github.com/cmu-delphi/delphi-epidata/pull/273).
Almost finished. Wait for the decision on `combined_symptoms` signals.

**Comment by krivard** [comment]
Combined symptoms signals have been approved with the following format:
* `sum_[symptom1]_[symptom2]_[raw|smoothed]_search`

**Comment by krivard** [comment]
I've approved the visual review. We've got reasonably good state coverage, with persistent exceptions of Alaska, Montana, Colorado, North Dakota, South Dakota, Vermont, Maine, and West Virginia. Compared with GHT the GS coverage is greater on average, though GHT's missingness tends to be more randomly distributed and less chronic in those particular states. Overall an improvement.

**Comment by benjaminysmith** [comment]
Thanks Katie.

@korlaxxalrok what is the status on automation?

@jingjtang it looks like the API documentation is nearly approved (waiting on a final review). Do you also have drafts for the signal pop up and mailing list notification?

**Comment by jingjtang** [comment]
@benjaminysmith Signal pop up text draft added [here](https://docs.google.com/document/d/1RLy4O-gtACVjLEVD_vxyPqvp9nWVhqEjoWAKi68RKpg/edit#) under `COVID Symptom Searches on Google `, waiting for a review @Akvannortwick

**Comment by benjaminysmith** [comment]
Thanks @jingjtang!

@Akvannortwick do we have a draft for the mailing list notification already?

**Comment by Akvannortwick** [comment]
@benjaminysmith working on the email to include all the new indicators for the 1.11 release.

**Comment by benjaminysmith** [comment]
Awesome. I believe that means we have all the documentation in progress/review and the only remaining step is to add to automation.

@krivard as FYI.

**Comment by korlaxxalrok** [comment]
@jingjtang @benjaminysmith Google Symptoms is on prod. It is currently scheduled to run one minute after Google Health Trends starting tomorrow. Is there any reason why we wouldn't want to ingest some data for today? I should be able to add it in before the metadata update kicks off later this evening.

**Comment by benjaminysmith** [comment]
Update: we decided to hold off on pushing to prod until Monday, but this is currently in progress. Marking automation as done.

**Comment by krivard** [comment]
Shipped in 1.11.
