### ISSUE TITLE
Release doctor-visits geo refactor

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#469]
- [Link to PR](https://github.com/cmu-delphi/covidcast-indicators/pull/401)
- Proposed release version: None; soon

This is another one just like #357: 

We went from a custom geo mapping file (for aggregating from (source geo TBD)->(county, hrr, msa, state)) to a central geo file based on rigorously sourced US census data.

Date of change is TBD; should be imminent. @mariajahja can confirm what day the changes were / will first be run in production.

@chinandrew are there any specific changes (eg [these](https://github.com/cmu-delphi/covidcast-indicators/pull/401#issuecomment-723712406)) we should mention in the API docs changelog or mailing list notification?

- [x] API [documentation](https://github.com/cmu-delphi/delphi-epidata/tree/main/docs/api) and/or [changelog](https://github.com/cmu-delphi/delphi-epidata/blob/main/docs/api/covidcast_changelog.md)
- [x] API mailing list notification

**Comment by chinandrew** [comment]
Doesn't hurt to mention we updated our geo mapping files for our indicators which may have very minor effects going forward, unless we think it'll add a bunch of unnecessary confusion

**Comment by mariajahja** [comment]
Just updated `bigchunk-dev-03.delphi.cmu.edu`, which runs the cron job to use the latest `dv-package` branch. New versions should be released tonight around 6:30p ET, unless any hiccups occur.

**Comment by krivard** [comment]
@chinandrew [the standard message for these geo refactors has been brief](https://github.com/cmu-delphi/delphi-epidata/blob/main/docs/api/covidcast_changelog.md#20-october-2020); sounds like you don't think anything beyond that is necessary. 👍

**Comment by chinandrew** [comment]
> @chinandrew [the standard message for these geo refactors has been brief](https://github.com/cmu-delphi/delphi-epidata/blob/main/docs/api/covidcast_changelog.md#20-october-2020); sounds like you don't think anything beyond that is necessary.

lgtm

**Comment by krivard** [comment]
Mailing list notification went out this afternoon.

**Comment by chinandrew** [comment]
isn't this kind of dependent on #502?
