### ISSUE TITLE
Get the ght tests for functions in `pull_api` to work without authentication

### ISSUE THREAD

**Issue by jingjtang** [cmu-delphi/covidcast-indicators#474]
The current unit tests coverage is good for all of the scrips except for `pull_api.py` since a large proportion of the code in that script requires ght-key (and internet) to pull data from the Google Health Trends API. 

Currently, just comment out those tests to maintain a dry-run mode for the ght unit tests. We might need to come up with a solution to testing those functions later.

**Comment by chinandrew** [comment]
This indicator is scheduled to be deprecated once goog symptoms is out right? If that's happening soon, might be simpler just to skip this issue.
