### ISSUE TITLE
Release Change Healthcare

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#479]
- [Link to issue](https://github.com/cmu-delphi/covidcast-indicators/issues/136)
- [Link to PR](https://github.com/cmu-delphi/covidcast-indicators/pull/320) (initial)
- Proposed release version: ASAP

Initial set of Change Healthcare signals to be released to the API as soon as possible.

- [x] API [documentation](https://github.com/cmu-delphi/delphi-epidata/tree/main/docs/api)
- [x] draft API mailing list notification and send to @Akvannortwick 

- [x] Statistical review (usually [correlations](https://github.com/cmu-delphi/covidcast/tree/main/docs/R-notebooks))
- [x] Signal / source name review (usually [Roni](https://docs.google.com/document/d/10hGd4Evce4lJ4VkWaQEKFQxvmw2P4xyYGtIAWF52Sf8/edit?usp=sharing))

**Comment by korlaxxalrok** [comment]
@krivard @rumackaaron

The indicator is deployed and scheduled in staging (currently for 9:30pm or so):

Ex. curl to see data:

```
curl -X GET 'https://api-staging.delphi.cmu.edu/epidata/api.php?source=covidcast&data_source=changehc&signal=smoothed_adj_cli&time_type=day&geo_type=hrr&time_values=20200201-202011010&geo_value=1'
```

**Comment by krivard** [comment]
All done! Indicator deployed in prod and scheduled to run at 9:43pm each day.
