### ISSUE TITLE
Migrate all indicators to a common export function

### ISSUE THREAD

**Issue by sgsmob** [cmu-delphi/covidcast-indicators#497]
We have a lot of replication of export code across indicators.  It doesn't appear that the functionality is actually that different across indicators, so we should build out `delphi_utils.create_export_csv()` and migrate all the indicators to use it.

Indicators that still need to be migrated:

- [x] `google_health`
- [ ] `nchs_mortality`
- [x] `quidel`
- [x] `quidel_covidtest`
- [x] `safegraph` (#574)
- [x] `safegraph_patterns`

**Comment by chinandrew** [comment]
safegraph_patterns looks like it used the original create_export_csv implementation, so checking it off

**Comment by chinandrew** [comment]
`nchs_mortality` uses epiweeks instead of days, so punting for now

**Comment by dshemetov** [comment]
Been diving into the `changehc` code recently. Seems like it could move to using this utility, at first glance. Would mostly need to pack the existing row data into a dataframe at the end of `update_sensor` and replace `write_to_csv` with a call to the export util. Thoughts @rumackaaron?
