### ISSUE TITLE
Automate all public signals

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#5]
Entails moving code to produce each into the covidcast-indicators repository. NB doctor-visits and fb-survey have restricted-access data sources, so for them we first need a way to test automation code on safe data.

Code ingestion:

- [x] doctor-visits
- [x] fb-survey
- [x] ght
- [x] jhu-csse
- [ ] indicator-combination

Verify new code produces same results as old code:

- [x] doctor-visits
- [x] fb-survey
- [x] ght
- [x] jhu-csse
- [ ] indicator-combination

Automation:

- [ ] doctor-visits
- [x] #1623
- [ ] fb-survey
- [x] ght
- [x] jhu-csse
- [x] usa-facts
- [ ] indicator-combination
- [ ] combination deaths signal

**Comment by korlaxxalrok** [comment]
I think this is ancient and we can close it. What do you think @nmdefries?
