### ISSUE TITLE
Release new batch of symptom survey signals

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#601]
- Issue: #323, #324 
- (no PR, code is already in `fb-package` branch)
- Proposed release version:  before December 10th

These signals make much more survey data available; see #323 and #324 for a list. cc @tildechris for the survey dashboard -- it will probably want to use these signals when available. Will you need signal description text in the usual doc for these? We don't want all of them on the map, but we could put all of them on the dashboard.

- [ ] API [documentation](https://github.com/cmu-delphi/delphi-epidata/blob/main/docs/api/covidcast-signals/_source-template.md) at https://github.com/cmu-delphi/delphi-epidata/pull/318
- [ ] API mailing list notification

- [ ] Statistical review (usually [correlations](https://github.com/cmu-delphi/covidcast/tree/main/docs/R-notebooks))
- [x] Signal / source name review (usually [Roni](https://docs.google.com/document/d/10hGd4Evce4lJ4VkWaQEKFQxvmw2P4xyYGtIAWF52Sf8/edit?usp=sharing)) (already done in the issues)
- [x] Verify licensing terms and any applicable DUA restrictions

- [ ] Visual review
- [ ] [Signal description pop-up text](https://docs.google.com/document/d/1kDqRg8EaI4WQXMaUUbbCGPlsUqEql8kgXCNt6AvMA9I/edit?usp=sharing) review
- [ ] [Map release notes](https://docs.google.com/document/d/1BpxGgIma_Lkd2kxtwEo2DBdHQ3zk6dHRz-leUIRlOIA/edit?usp=sharing)

**Comment by krivard** [comment]
[Trying out tracking this work using a template issue in asana](https://app.asana.com/0/0/1199543901311642/f)
