### ISSUE TITLE
Add PCR tests signal from COVID Act Now

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#680]
To start out with we'd like to mirror and reaggregate PCR testing information. Some research into CAN's available metrics and methodology will be required to determine whether this is actually possible; a cursory look through their documentation suggests that they do not actually specify what kinds of tests are included in their metrics, or whether they count number of tests or number of people tested. Both will need to be confirmed before we start writing code.

cc @tildechris 

**Data details**
 
https://apidocs.covidactnow.org/

**Additional context**

CAN's API terms of use specifies a CC BY-NC-ND license, which would normally prevent reaggregation. However, we have received special permission from CAN to produce derivative data streams from their data so long as we refrain from commercial use. Essentially we've been given a CC BY-NC license, which fits easily within COVIDcast's established data licenses.

**Comment by eujing** [comment]
Current update for the nature of their test positvity metrics:

Based on previous discussions in the #can-delphi channel, there are two possible ways for obtaining test posivity metrics from CAN, either from:
1) Their API directly as `testPosivityRatio`, or 
2) Their latest parquet file using the `pcr_test_*` test result count columns

Each obtains the metrics from a mixture of sources for greater geo coverage, and also explicity specifies a `source` and `provider` for each unit of time and geo.

 `testPositivityRatio` from their API has the following sources (in descending geo coverage):
1) CDCTesting: PCR and specimen-based
2) Valorum: Not confirmed yet
3) Others: Not confirmed yet
4) CMSTesting: PCR and specimen-based

Parquet file `pcr_test_*` columns have the following `providers` (in descending geo coverage). The first two are used for county-level metrics, CTP is used for state-level metrics:
1) CDC: PCR and specimen-based
2) State: Not confirmed yet
3) Covid Tracking Project: CTP has quite a detailed breakdown of PCR vs Antibody and Specimen vs People counts, but still need to confirm if specimen-based counts are used here.

It seems that majority of the metrics are PCR and specimen-based, but I am currently waiting for confirmation from CAN on the remaining sources. From my current understanding, Valorum and State are based on state dashboard scrapers, so it might be harder to confirm for those.

**Comment by tildechris** [comment]
Our intended measure is percent of positive PCR tests vs. all PCR tests right?  So, we need to confirm we're only looking at PCR on a specimen-basis?

**Comment by eujing** [comment]
Yeah, we need to confirm if all the sources are PCR on a specimen-basis
