### ISSUE TITLE
Fix failing claims_hosp build

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#685]
https://github.com/cmu-delphi/covidcast-indicators/pull/684/checks?check_run_id=1689109702

```
ERROR: Could not find a version that satisfies the requirement pylint
ERROR: No matching distribution found for pylint
```

It builds and installs fine on my local machine, so this is probably some kind of CI-environment-specific dependency hell problem. 😞 

cc @benjaminysmith @mariajahja

**Comment by chinandrew** [comment]
:/ thats new. looking into it

**Comment by chinandrew** [comment]
uh I just reran it and it passed..... maybe some weird intermittent pip glitch?
