### ISSUE TITLE
Align approaches to mixing for symptom survey aggregates

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/covidcast-indicators#764]
The old pipeline for community responses did not apply mixing. To reproduce it, we currently ignore the mixed weights for some aggregates. Once a better mixing/weighting scheme is chosen, all signals should use it. Once a new approach is chosen, we may need to reissue old signals or update public-facing documentation about the change.

**Comment by capnrefsmmat** [comment]
I believe we can shift to mixing all signals. I'm told that trimming weights is standard practice, and we can adopt this for consistency.
