### ISSUE TITLE
[fb-survey] Qualtrics file should supersede archive data, not the other way around

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#810]
[This PR](https://github.com/cmu-delphi/covidcast-indicators/pull/794) was merged after the new 2-doses signals were already being generated in pseudo-production. This occurred during the bigint data outage, and while we dropped the affected files from the issue backups and scrubbed what had been loaded into the database, the miscoded variables did make it into the archive file. When the pipeline was updated with the code from the merged PR, we assumed that the corrected coding would be applied when those rows were updated in the archive with the new data from that day's Qualtrics files.

This did not happen. Instead, previously-reported days continued to use the bad variable coding, and only the one additional fresh day seemed to use the corrected coding. When we dropped back to a version of the archive from before Wave 8 and re-ran with the same Qualtrics files, all days used the correct coding.

This seems to indicate that the code is not applying the archive correctly when the archive and the Qualtrics files disagree. The code should use the response timestamp to determine the correct response row for the cid, but once that has been done, if both the Qualtrics file and the archive have a record, we should prefer the Qualtrics file, re-coding as necessary.

**Comment by nmdefries** [comment]
CTIS has concluded.
