### ISSUE TITLE
Fix JHU US Territories Prop Signals

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/covidcast-indicators#829]
**Actual Behavior:**

Currently, the prop signals for the US Territories American Simoa, Guam, Virgin Islands, and Northern Mariana Islands give either nan or inf values in JHU.

**Context**

The issue is with JHU's reporting and how we store the population data. For example, doesn't report the FIPS codes

```
60010,23030
60020,1143
60030,0
60040,17
60050,31329
```

But it does report 60000. So the 60000 code gets 0 population (as megafips do) and when doing add_population the counties that do contain pop data don't get added in. So the result is a population of 0 when aggregating to any geo higher than county.

A possible solution is to just divide by a pre-computed state/hhs/nation population for territories.

**Comment by krivard** [comment]
Notes from Slack:

Cases & Deaths are the only data sources that use megafips for something other than an aggregation of censored counties.

JHU is the only Cases & Deaths data source that reports megafips on a region _without_ also reporting all fips for that region.

Preferred solution here is to add special handling to JHU only, being careful not to accidentally double the population for Puerto Rico (the only territory for which JHU reports fips).
