### ISSUE TITLE
Momentary drop in fb-survey sample size on Bigint Day

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#873]
**Actual Behavior:**

```r
covidcast_signal('fb-survey', "raw_cli", start_day="2021-01-01", geo_type="nation") %>% ggplot(aes(x = time_value, y=sample_size)) + geom_line()
```
![Screen Shot 2021-02-26 at 5 17 46 PM](https://user-images.githubusercontent.com/711629/109361208-8d6a3300-7856-11eb-9717-dba96268df7f.png)

That dip is 2762 observations on 2021-02-04.

**Expected behavior**

No weird dip on 2021-02-04.

**Context**

Coincidentally, 2021-02-04 was the Bigint Catastrophe Day, though I don't know how that could make us lose sample size.

**Comment by capnrefsmmat** [comment]
Facebook noted a sampling issue may have affected response rates on 2021-02-01, so we should check against the microdata in case their timing was off and this is actually it.

**Comment by krivard** [comment]
We're going to have to reissue Wave 8 anyhow. @nmdefries should double check that there's no corresponding dip in the raw data and microdata, and if there isn't, then I'll just extend the Wave 8 reissue back to Feb 1 instead of Feb 8.

**Comment by nmdefries** [comment]
There's no dip in sample size on Feb 4 in the raw data (n = 54k), microdata (46k), or nation_raw_cli (41k), so we can go ahead with the reissue.

**Comment by krivard** [comment]
On it

**Comment by krivard** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/1158666/111530006-31018180-8739-11eb-87bf-bd9d69913683.png)
