### ISSUE TITLE
changehc indicator outputs no data for hhs, nation when data is present at lower geo levels

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#881]
[[Slack] context](https://delphi-org.slack.com/archives/C01LZ3A2UMU/p1614698588017700?thread_ts=1614663716.017100&cid=C01LZ3A2UMU)

In the changehc indicator, it seems to be possible for county/state/hrr data to pass minimum denominator thresholds when hhs/nation data does not. Our current hypothesis is that this is due to smoothing numerators and denominators separately and after geo aggregation: the smoother is being overly enthusiastic about curve fitting, such that some counties/state/hrrs may be concave-up when the majority of their siblings are concave-down, causing the overall curve for hhs or nation to fall below threshold.

There are several suspicious things going on here:
* Smoothing after geo aggregation (though doctor-visits also does this)
* Smoothing the numerator and denominator separately before computing the rate
* Backfill causes the counts to be artificially low for the most recent period of data, and the smoother is probably not a good tool for modeling this effect
* ~Zero-filling (iirc the smoother expects NaNs, not zeros)~ (this turns out to be true zeros -- by definition CHNG does not report if the count is 0)
* No corner-case tests, only completion tests
* ~[how did this ever work](https://github.com/cmu-delphi/covidcast-indicators/blob/ca43cda9ffd3e321369ad7911c5d8f44a1feb70a/changehc/delphi_changehc/sensor.py#L152)~ (turns out pandas assigns NaNs for the remaining indices, which is fine)

To fix:
* Write a test that fails when the relationship between having-data is not hierarchical
* Consider smoothing ratios instead of numerators/denominators
* Switch to using raw denominators for thresholding
* Consider whether backfill is adding 2x smoothing
* Consider reducing the bandwidth? though this would have other ramifications

[Sample data](http://rinkitink.ml.cmu.edu/delphi/misc/bad_spiky_business.csv)

**Comment by RoniRos** [comment]
> There are several suspicious things going on here:
> * Smoothing after geo aggregation (though doctor-visits also does this)

I think smoothing _must_ be done after geo-aggregation, not before. do you agree?

**Comment by krivard** [comment]
I generally expect the following to be true for both smoothed and unsmoothed signals:

```
pa_state_df = covidcast.signal(...)
pa_counties_df = covidcast.signal(...)
censored_pa_counties_df = [...magic...]
sum(pa_counties_df) + sum(censored_pa_counties_df) == pa_state_df
```

which would imply smoothing before aggregation, no?

**Comment by RoniRos** [comment]
Hmm..  why not the following?
1. Aggregate unsmoothed, uncensored counts to all geo-levels.
2. From here on, treat each geo-level separately, for the purpose of censoring, smoothing, magic, etc.

**Comment by krivard** [comment]
just to verify I'm reading you right -- if you fetched data like this from our API, you would not find it suspicious?

```
signal: smoothed_count
region  value
hhs1    10
hhs2    10
hhs3    10
hhs4    10
hhs5    10
hhs6    10
hhs7    10
hhs8    10
hhs9    10
hhs10   10
usa     90
```

**Comment by RoniRos** [comment]
Perhaps, but the documentation should explain it.

- Smoothing is done primarily due to small counts.  Even when it's done for other reasons (e.g. temporal fluctuations), the absolute magnitude of the counts is very relevant for determining the appropriate amount of smoothing.  Therefore, when geo-aggregating, we need to know the actual aggregated counts before smoothing.
- Smoothing is data manipulation, which may or may not be desired by the end user (which is why we should give the user the choice of whether and how to do it);  Smoothing implies some modeling assumption.  In contrast, aggregation is straightforward and makes no assumptions.    

The apparent inconsistency above does not seem problematic to me (it _would_ be problematic if it held for the unsmoothed counts).  But perhaps there were other reasons to do smoothing before aggregation -- we should figure out who was involved in that decision, and ask them.

**Comment by krivard** [comment]
Okay, I'm happy with that. 

I will note that we have tons of signals for which we do not publish the unsmoothed values (doctor-visits, hospital-admissions,  chng, the majority of the survey signals). In cases where we decided not to publish unsmoothed values because we wanted to conserve database space, we can and should switch to providing both smoothed and unsmoothed values once we have the API server infrastructure available for performing smoothing at query time. However, I suspect we decided not to publish unsmoothed values for doctor-visits for either data privacy or DUA reasons, which would prevent us from giving users that choice.

**Comment by RoniRos** [comment]
Agreed.  

That check could be made at query-time and be source/signal-specific.  However, this introduces a vulnerability, where the restricted information is in the DB and is protected only by the integrity of the API code.  Which means that the DB itself is vulnerable if hacked.  

An alternative might be to only store smoothed values in these cases.   Another alternative, assuming we shard the DB, is to specially designate and protect those shards which contain restricted information.
