### ISSUE TITLE
Mask signal unavailable on 2021-02-24

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/covidcast-indicators#933]
**Actual Behavior:**

```
> covidcast_signal("fb-survey", "smoothed_wearing_mask_7d", geo_type="nation", start_day="2021-02-20", end_day="2021-03-01") %>% select(time_value, value, issue, sample_size)
Fetched day 2021-02-20 to 2021-03-01: num_entries = 9
A `covidcast_signal` data frame with 9 rows and 4 columns.

  time_value    value      issue sample_size
1 2021-02-20 93.42923 2021-02-21      226327
2 2021-02-21 93.36144 2021-02-22      228068
3 2021-02-22 93.25664 2021-02-23      227445
4 2021-02-23 93.10097 2021-02-24      227589
5 2021-02-25 92.72136 2021-03-02       97634
6 2021-02-26 92.72283 2021-03-03      128435
7 2021-02-27 92.70434 2021-03-04      160855
8 2021-02-28 92.67395 2021-03-05      194954
9 2021-03-01 92.64141 2021-03-06      228025
Warning message:
Data not fetched for the following days: 2021-02-24 
```

Something is also wrong on 2021-02-25, since that sample size drop should not be there. Something got reissued on 2021-03-02 incorrectly?

`smoothed_cli` and other signals seem fine; I've only seen this problem with `smoothed_wearing_mask_7d` and `smoothed_wwearing_mask_7d`.

Also, @benjaminysmith, isn't this the type of gap that SirCAL should be reporting? Or maybe SirCAL only checks for gaps in recent data, but this was a reissue of older data, so it didn't check? Maybe we should extend the window it checks for.

**Comment by krivard** [comment]
I expect both this and #873 to resolve with the reissue we're doing for #928.

SirCAL only checks the last 7 days. We can consider extending the window backwards, but that will extend the running time, and it already takes ~30 minutes.

It might be more appropriate to start tuning validation parameters for the facebook indicator, so that we'd capture the gap at data generation time.

**Comment by krivard** [comment]
Fixed:
```
> covidcast_signal("fb-survey", "smoothed_wearing_mask_7d", geo_type="nation", start_day="2021-02-20", end_day="2021-03-01") %>% select(time_value, value, issue, sample_size) 
   time_value    value      issue sample_size
1  2021-02-20 93.42923 2021-03-17      226327
2  2021-02-21 93.36144 2021-03-17      228068
3  2021-02-22 93.25664 2021-03-17      227445
4  2021-02-23 93.10097 2021-03-17      227589
5  2021-02-24 93.01160 2021-03-17      227669
6  2021-02-25 92.90432 2021-03-17      226651
7  2021-02-26 92.81578 2021-03-17      225862
8  2021-02-27 92.74943 2021-03-17      227781
9  2021-02-28 92.69863 2021-03-17      228196
10 2021-03-01 92.63751 2021-03-17      227877
```
