### ISSUE TITLE
New indicator: CDC vaccine data

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#951]
We would like to save multiple CDC signals for vaccines. It would be great if we could easily access:

P0 - 
- [ ] Number of people partially vaccinated
- [ ] Number of people fully vaccinated
- [ ] Stratify by which vaccine administered

P1/P2 - 
- [ ] Vaccination site
- [ ] Vaccine Demographics 
- [ ] Stratify by general population or long-term-care facility

Temporal resolution:
- [ ] daily incidence
- [ ] 7-day-average incidence
- [ ] daily cumulative

Geographic resolution: county, hrr, msa if you can get it that detailed, otherwise just state, hhs, nation

The proposed sources are : 

1. https://covid.cdc.gov/covid-data-tracker/#vaccination-trends (center of page "Data Table for Trends in Number of COVID-19 Vaccinations in the US" - breakdowns by date

2. https://covid.cdc.gov/covid-data-tracker/#vaccination-demographic - to see the changes in teh demographics 

3. https://covid.cdc.gov/covid-data-tracker/#vaccinations - breakdown by type of vaccine 

4. https://covid.cdc.gov/covid-data-tracker/#vaccinations (center of page "Data Table for Trends in Number of COVID-19 Vaccinations in the US" - breakdowns by state

5. https://data.cdc.gov/browse?q=COVID%20vaccine&sortBy=relevance TBD Which ones are the most informative

**Comment by Ananya-Joshi** [comment]
All these csvs are now being saved at: http://wprdc-backup.s3-website.us-east-2.amazonaws.com/
Most relevant files are in the CDC_vacc folder

**Comment by krivard** [comment]
Dan shared an additional CDC link:

https://data.cdc.gov/Vaccinations/COVID-19-Vaccinations-in-the-United-States-County/8xkx-amqh

**Comment by Ananya-Joshi** [comment]
There's no data for Texas or Hawaii on the CDC Data csv - should I try to supplement these sources or just put a warning that we don't have data for those states (and some select counties in VA, CA).

**Comment by krivard** [comment]
leave supplements for v2
